### ISSUE TITLE
Use zustand for local state management?

### ISSUE THREAD

**Issue by smeijer** [react-spring/zustand#101]
I'm curious if it's possible to use zustand for local state management, instead of using `React.useState`.

Can we construct multiple instances of the same store? And can that instance be bound to the lifecycle of the component?

**Comment by drcmda** [comment]
you can do that, and you can make as many instances as you like.

**Comment by smeijer** [comment]
Do you have an example? I feel like I need to manage the instances myself. Is that correct?

**Comment by clawoflight** [comment]
Instead of exporting the result of the call to create(), simply export a function that will call create for you and easily create a store.

**Comment by smeijer** [comment]
> Instead of exporting the result of the call to create(), simply export a function that will call create for you and easily create a store.

You mean like the code below? That's not going to work, as we need to have the same store instance across renders.

```jsx
import create from 'zustand'

const getStore = (initialCount) => create(set => ({
  count: initialCount || 0,
  increase: () => set(state => ({ count: state.count + 1 })),
  reset: () => set({ count: 0 })
}));


function Counter() {
  const [useStore] = getStore();
  const count = useStore(state => state.count)

  return (
    <>
      <h1>{count}</h1>
      <button onClick={increase}>up</button>
    </>
  );
}
```

**Comment by clawoflight** [comment]
@smeijer you would need to wrap the call in `useEffect` so that it is only executed once.
Better yet, just export a hook that calls `useEffect` for ease of use :)

**Comment by smeijer** [comment]
Thanks. I created such a hook by persisting the store in a `useRef`. I do think it's worth adding such a hook to the project, and adding the example to the readme though.

**Comment by zslabs** [comment]
@smeijer 👋 Have a complete example handy that you could add a PR with?

**Comment by smeijer** [comment]
Hi @zslabs, we decided to not move forward with zustand, so the hook has been lost. Sorry I can't help you.

**Comment by dai-shi** [comment]
https://github.com/react-spring/zustand/issues/128#issuecomment-673217928

Creating a store in a render function is not recommended. Can you create all stores in advance?

**Comment by dai-shi** [comment]
```js
const [useStore] = useState(() => create(...))
```
This seems to work as of writing. Use it with caution not to break the rule of hooks.

Closing this. Please reopen #128 for further discussion.
