### ISSUE TITLE
Frequent updates to the store and performance

### ISSUE THREAD

**Issue by tommhuth** [react-spring/zustand#102]
A general question about performance: say you have some data that changes insides a `requestAnimationFrame` and you want that data stored in `zustand`. Is it a bad idea to do those kinds of frequent updates to the store? In my case I'm storing a position (so basically just an object with a `x`, `y ` and `z` property) which would then be updated 60 times per second.

(Of course my components do not consume the data via the normal hook, but use the `subscribe`  method API instead.)

**Comment by clawoflight** [comment]
Have a look at the high-performance example in the README, that should give you a good idea of what's possible :)

**Comment by tommhuth** [comment]
thanks! does that mean that frequent updates are OK, as long as they aren't consumed via render (`useStore`)?

**Comment by clawoflight** [comment]
Yes, as long as you can directly do something with the updates without re-rendering components all the time.
In the example, he directly modifies the DOM (through a ref) in a subscription callback, outside the react render tree.

**Comment by dai-shi** [comment]
Seems like this is resolved.
