### ISSUE TITLE
Question: How to prevent re-render?

### ISSUE THREAD

**Issue by Pirastrino** [react-spring/zustand#103]
Hi,
when I have `const { someValue } = useStore();`, which I use in two or more different function components, some of them may be unmounted then I am getting an error -> _Can't perform a React state update on an unmounted component_.

So my question is how can I prevent re-render of a component which uses some stored values when unmounted?

**Comment by rdhox** [comment]
Did you try selecting your value ?

```js
const someValue = useStore(state => state.someValue);
```

**Comment by dai-shi** [comment]
If the above doesn't work, I guess this is the same as #109
