### ISSUE TITLE
How can I remove something from a store?

### ISSUE THREAD

**Issue by richardgorman** [react-spring/zustand#105]
Let's say I have a store and I initially set it with something like:
```js
store.setState({
  a: { ... },
  b: { ... },
})
```

Then, for some reason, **b** no longer exists and should be removed. How can I remove it (since setState always merges)?

**Comment by drcmda** [comment]
you can overwrite it, like { a: undefined, b: undefined }, this is exactly how setState worked in react. @JeremyRH was in favour of switching this behaviour from merge to set, then it would be a little easier. perhaps we could think about this again when attempting a new major.

**Comment by richardgorman** [comment]
Personally, I really like that the state is merged by default. It saves a lot of extra code to manually merge new with existing state. However, I can think of numerous cases where overriding state outright can be useful.

Perhaps a flag during the `setState` call would be enough and then both cases are covered. Also then a new major would not be necessary.

Additionally, it might be prudent, to disable/enable merging by default when creating a store.

**Comment by dai-shi** [comment]
Fixed by #137.
