### ISSUE TITLE
Pushing an object in an array of the store

### ISSUE THREAD

**Issue by Franckapik** [react-spring/zustand#107]
I have this : 
const [useStore, api] = create((set, get) => ({
  connected : false,
  players : [],
  count: 2,
  id: 0,
  inc: () => set(state => ({ count: state.count + 1 })),
}))

and i would like to add a player in players array.

const addplayer = (listeId) => {

  listeId.map((ident, i) => {
    console.log(ident);
    let player = {
      id : ident,
      score : 0,
      x : 0,
      y : 0,
    }
      api.setState(state => ({players : [state.players, player]})); 
  })
}

Is this the best way to do this? It didn't seems to work in my project now but maybe somebody could help me on this...

Thank you by the way for your work !!
F.

**Comment by Franckapik** [comment]
Ok the answer was to use this line instead with spread syntax : 

api.setState(state => ({players : [...state.players, player]}));

Is this possible to make put this function like a method in create store ?

**Comment by clawoflight** [comment]
yes, just like `inc: () => set(state => ({ count: state.count + 1 }))` in the example.
If you need to do things like this often, have a look at `immer`.

**Comment by Franckapik** [comment]
Thank you @clawoflight , i just install immer, so usefull now :)

**Comment by clawoflight** [comment]
:)
If you are satisfied, feel free to close the issue - there are many open ones here and the maintainers are probably losing the overview.
