### ISSUE TITLE
SSR example

### ISSUE THREAD

**Issue by mcansh** [react-spring/zustand#11]
I think I almost have it working using a tweaked version of the redux [next.js example](https://github.com/zeit/next.js/blob/canary/examples/with-redux/lib/with-redux-store.js), but the state gets wiped out on the client

**Comment by drcmda** [comment]
I think I would need some help for that, I don’t understand ssr good enough, but would gladly welcome prs.

**Comment by codemilli** [comment]
I tried to set the default state with storeApi but This package is based on `React Hooks` and using `useLayoutEffect` hooks.
That is problem that makes server side rendering broken.
Is there any other way to set default state dynamically without update DOM?

**Comment by drcmda** [comment]
could you explain why useLayoutEffect is a problem when it comes to SSR?

**Comment by codemilli** [comment]
@drcmda 
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
```
Above  error message is kept being logged. 
I found `react-redux` uses `useLayoutEffect` only if `window` is defined or uses `useEffect`. 
```javascript 
typeof window !== 'undefined' ? useLayoutEffect : useEffect
```
Can it be the solution to this case? 

Related issue: https://github.com/facebook/react/issues/14927

**Comment by drcmda** [comment]
yes, i guess that could be. could you try? could you try? you can copy this: https://unpkg.com/zustand@0.2.1/dist/esm/index.js into a local "zustand.js" and change it to useEffect. if it works i'll implement the patch.

**Comment by codemilli** [comment]
@drcmda 
Okay ! i will make a pr :D

**Comment by themre** [comment]
can this issue be closed? does it work? thanks!

**Comment by janek26** [comment]
https://github.com/zeit/next.js/pull/11222

**Comment by ahmedu007** [comment]
That PR never landed in the repo 😞

**Comment by maxwaiyaki** [comment]
Can we revisit this issue?? Seems there was never a solution implemented.

**Comment by dai-shi** [comment]
Hi, is it about hydration not working, or is it completely broken with next? Would you like to file a new issue please?

Note: useIsoLayoutEffect is just a hack to eliminate the warning message. It doesn't do anything for SSR.

**Comment by dai-shi** [comment]
Let me reopen this.

@jd327
https://github.com/react-spring/zustand/issues/182#issuecomment-689268271

> I'm currently supplementing with createContext and useContext for anything SSR-related 

Where can I find such examples with useContext, so that I can start learning? There must be something in the nextjs docs.

**Comment by dai-shi** [comment]
I changed my mind. Let me close this and continue discussion in #182.
