### ISSUE TITLE
Fast Refresh

### ISSUE THREAD

**Issue by kennetpostigo** [react-spring/zustand#111]
I'm running into cases where fast-refresh breaks when using zustand, not exactly sure why tho. If I remove zustand fast-refresh start working again

**Comment by ajsmth** [comment]
I'm having a similar issue but in reverse - fast refresh leads to the selectors not firing when I update a store.

**Comment by a-eid** [comment]
for me fast refresh, kinda resets some of my state, ( need to investigate it more. ).

**Comment by dai-shi** [comment]
HMR not working in codesandbox. I assume they are using FastRefresh.

**Comment by drcmda** [comment]
they do, but only if index.js is a clean `ReactDOM.render(<App/>,...)` and code is exposed in App.js.

**Comment by dai-shi** [comment]
Hmm, is this clean?
https://codesandbox.io/s/bold-bassi-v2fhq?file=/src/index.tsx

**Comment by a-eid** [comment]
it doesn't trigger a re-render after RN fast refresh is triggered.

**Comment by drcmda** [comment]
@dai-shi yes fastrefresh is enabled at least

**Comment by drcmda** [comment]
the reset, i think that's just how fast refresh works. if you put the store into its own module it works as expected: https://codesandbox.io/s/dry-river-30mml?file=/src/App.tsx i doesnt seem like that's in our hands even, the store is a singleton that's outside of react. it wipes out the module and resets all singletons.

**Comment by drcmda** [comment]
@dai-shi just noticed that v3 fixes it: https://codesandbox.io/s/dry-river-30mml?file=/src/App.js

**Comment by kennetpostigo** [comment]
@drcmda is there any timeline for v3?

**Comment by drcmda** [comment]
today? tomorrow? something like that :-)
