### ISSUE TITLE
Typescript problem with StateListener

### ISSUE THREAD

**Issue by rdhox** [react-spring/zustand#114]
Hey!

I use this block of code:

```js
  export interface NetWorkInfo {
    isInternetOn: boolean;
    type: NetInfoStateType;
    isConnectionExpensive: boolean;
    cellularType: NetInfoCellularGeneration | 'null';
  };

  ...

  useEffect(() => {
    const unsubIsInternetOn = apiApp.subscribe<NetWorkInfo>(
      networkInfo => {
        const { isInternetOn } = networkInfo;
        setIsInternetOn(isInternetOn);
      },
      appState => appState.state.networkInfo
    );

    return () => {
      unsubIsInternetOn();
    };
  }, []);
```

And TS is never happy about the first param of subscribe: 
`Property 'isInternetOn' does not exist on type 'NetWorkInfo | null'.`

Because of the `null` [here](https://github.com/react-spring/zustand/blob/d8f8c5f752465065959b3e6782774b316881f72a/src/index.ts#L13).

Is there a reason why the param1 of StateListener should be null ?

Thanks!

**Comment by dai-shi** [comment]
In case of error, it will be `null`.

For now, you need to check it on your end.
```js
      networkInfo => {
        if (networkInfo === null) return; // or report error
        const { isInternetOn } = networkInfo;
        setIsInternetOn(isInternetOn);
      },
```

cc @drcmda We could revisit this in v3. I think throwing an error is reasonable.

**Comment by rdhox** [comment]
Thanks for your answer.
I find a way around to make TS happy:
```typescript
useEffect(() => {
    const unsubIsInternetOn = apiApp.subscribe<NetWorkInfo>(
      networkInfo => {
        const { isInternetOn } = networkInfo as NetWorkInfo;
        setIsInternetOn(isInternetOn);
      },
      appState => appState.state.networkInfo
    );

    return () => {
      unsubIsInternetOn();
    };
  }, []);
```

**Comment by dai-shi** [comment]
That's fine too as long as you are sure that your selector never throws.

> We could revisit this in v3. I think throwing an error is reasonable.

This was my misunderstanding. We need a way to report error via listener.

Closing this.
