### ISSUE TITLE
inconsistent behaviour with strict mode and useEffect

### ISSUE THREAD

**Issue by beeglebug** [react-spring/zustand#115]
I have a component which is subscribed to `value` from my store, which it uses in it's render output. I attempted to add a useEffect which would trigger when value changed, and perform some side effect, e.g:

```javascript
function Effect() {
  const value = useStore(state => state.value);

  useEffect(() => {
    someSideEffect(value)
  }, [value]);

  return value;
}
```

I noticed that the useEffect wasn't firing when the value changed, despite the rendered output updating.

Eventually i reduced this down to `React.StrictMode`, if i remove this, everything works how I expect it to, but when it's on, value changing just caused the component to render 4 times with no useEffect calls.

Minimal example: https://codesandbox.io/s/hungry-hoover-khx8k

But! It gets even weirder than that... 😫

If you look in the codesandbox, you can see that when using StrictMode, calling `test()` in the console will not cause the effect to fire, but pressing the button, which fires the same update function, only grabbed via `useStore`, works fine.

There is also a version of the Effect component in the sandbox which uses the more direct `api.subscribe` style of useEffect, and this one works with both the button and the `test()` function call, even with strict mode turned on.

I can't get my head around it. Am I doing something wrong?

**Comment by beeglebug** [comment]
The more i look into this the less I think it's anything to do with with zustand itself. 

Both methods of causing a state change (a useStore selected function, or api "global"), cause the store update to happen, the useStore returns a changed value to the component, and the component re-renders, it's only the useEffect which gets skipped, which is outside of zustands control.

Having said that, i'd still be curious to know why the disparity, and it might be worth pointing out as a gotcha in the readme if the behaviour is consistent.

**Comment by rdhox** [comment]
In your example (which make no use of zustand btw), there is lot of mistakes about the use of React and JavaScript in general.
I really encourage you to follow tutorials on https://reactjs.org/ to have a better understanding of it.

**Comment by beeglebug** [comment]
God - sorry that's me, I was messing about with something and didn't realise i'd saved over the original codesandbox, let me try and revert.

**Comment by beeglebug** [comment]
Right, that should have it back to the original minimal reproduction of the original issue, sorry about that.

**Comment by rdhox** [comment]
Ok no problem, I understand better now!

So first problem I see, is that React component should always return JSX elements (or null at some occasion). So your two components Effect are working because of how JavaScript works, but it mainly gonna make React having a abnormal behavior. 

Also in case, the strict mode has some particularity to know about in dev mode:
 *  https://reactjs.org/docs/strict-mode.html
 *  https://medium.com/@andreasheissenberger/react-components-render-twice-any-way-to-fix-this-91cf23961625

Here your sandbox that has a normal behavior:
https://codesandbox.io/s/zustand-use-effect-9eco4

For the useEffect, not being call when using the function `test` in the console in strict mode, it's a React behavior. To be honest, I don't know all the details here (React fiber architecture is not that simple ^^). I think that the strict mode imply some change during the commit phase and the calls of lifecycle events.

In your situation, React don't know what triggered the update since the call is from the window object and not from a React Component (React keep in memory all the tree of components and their states with JS objects call fibers for each component). And so the correct behavior of React is not triggered by the `test` function and your life cycle effect is not call, but React style do the job by rerender the view with the new state.

You can post an issue of this behavior on the React repo, I'm sure you will have a complete response!

**Comment by beeglebug** [comment]
Thanks for the input!

I've taken a look at your modified codesandbox, and I can't see any functional differences from the original. The bug occurs exactly the same for me.

> React component should always return JSX elements

Both null and string are valid return values for ReactNode (if they weren't you'd see warnings in the console), so that's not it. 

> strict mode has some particularities

All strict mode should be doing here is re-running the render methods, it's doing what i'd expect from a render perspective. Per the docs, StrictMode is designed to highlight unintended side effects, and useEffect is all about _intended_ side effects.

>In your situation, React don't know what triggered the update since the call is from the window object and not from a React Component

React is fully aware that an update happened, that's why it re-renders. The issue is why the effect is skipped when the dependency has clearly changed.

If you look at the zustand source code you can see that it uses a little trick with an incrementing useReducer value which forces components using the store to see the changes, even when done from outside the React tree. This is an advertised feature of zustand in the readme, and an important part of why it's such a great library! 

Fundamentally I still can't see why calling `test()` should be any different to calling the version inside a react component, and crucially, why this is different only in strict mode.

Like I said earlier, this might well actually not be anything to do with zustand, but a weird React gotcha i wasn't aware of. But even if it is, it's probably worth noting in the readme as it's caused quite a few headaches in my team by not behaving as expected.

**Comment by JeremyRH** [comment]
@beeglebug This seems to be an issue with synchronous updates and React.StrictMode.

https://codesandbox.io/s/sad-elion-o8ohl?file=/src/index.js

**Comment by beeglebug** [comment]
Thank you! That's exactly the kind of thing I was trying to put together
earlier to try and take zustand out of the equation.

I'm glad I'm not going mad, this has been bugging me for days!

I guess that means this issue should be closed though. Although possibly
worth mentioning in the readme if it's a known React issue which affects a
common use case?

**Comment by rdhox** [comment]
>If you look at the zustand source code you can see that it uses a little trick with an incrementing useReducer value which forces components using the store to see the changes, even when done from outside the React tree. This is an advertised feature of zustand in the readme, and an important part of why it's such a great library!

The important point is not the use of useReducer outside of the React tree by zustand, it is the event that triggered it. In the [React doc](https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison):

 _Legacy mode has automatic batching in React-managed events but it’s limited to one browser task. Non-React events must opt-in using unstable_batchedUpdates. In Blocking Mode and Concurrent Mode, all setStates are batched by default._

The render phase works, but there is something going on with the commit phase, and it's where my core React knowledge are too limited to know if it's actually an issue or a normal behavior.

Note that once you use `unstable_batchedUpdates` in your example, the useEffect is working:

https://codesandbox.io/s/zustand-use-effect-8gpis

**Comment by beeglebug** [comment]
Ahhh ok, yeah I think I get it now. It's not so much that the code itself
is outside the react tree, but the event that triggers the state change was
a react synthetic event (the click handler on the button in this case).

I'm not sure this gets me any closer to a workable solution, but it sure is
expanding my knowledge of react inner workings, so thanks again for your
help.

**Comment by dai-shi** [comment]
Sorry, I don't quite follow the discussion, but could we close this?

**Comment by JeremyRH** [comment]
Yes, we can close this unless we want to document this behavior somewhere. I think it's too much of an edge-case and will not exist in concurret mode or when using useMutableSource.
