### ISSUE TITLE
Framework-agnostic store

### ISSUE THREAD

**Issue by olavoasantos** [react-spring/zustand#118]
Hi.

Just recently I ran into this library and I really like the API. One thing I noticed is that the implementation is tied to React. While this is not necessarily a bad thing, but, with a few tweaks, you could widen the usage of the library to realms beyond.

I tinkered around with the code and made it work like this:

```TypeScript
export default function create<TState extends State>(
  createState: StateCreator<TState>
): [UseStore<TState>, StoreApi<TState>] {
  const store = createStore<TState>(createState);
  const storeHook = useStore<TState>(store);

  return [storeHook, store];
}
```

Based on this, there were no breaking changes to the current API (just had to expose `createListener: CreateListener<T>` and `listen: Subscribe<T>` on the `StoreApi` interface). Now, if a given user wants to use Zustand without React, they could use the `createStore` function.

I'm not sure if this interests the maintainers, but I could open a PR if it is:
https://github.com/react-spring/zustand/compare/master...olavoasantos:feat-fw-agnostic-store

**Comment by olavoparno** [comment]
Doesn't useStore still use React? I mean, this is not regarding to the implementation itself but... anyway, cool. Could you provide us with some examples of usage outside of React's ecosystem? This would be incredibly nice.

**Comment by olavoasantos** [comment]
Yes. `useStore` still uses React, but if I don't need React, I could just call `createStore` instead of `create` and I'd still have the functionality. I'm gonna try to write an example of this for Vanilla JS, but I think it's quite possible to adapt to other frameworks as well.

**Comment by dai-shi** [comment]
For now you could do:
```js
const [, store] = create(...);
```
We are revisiting this signature for the next major.

It still depends on React.
cc @drcmda Another use case for `import { useStore, create } ...`.

**Comment by drcmda** [comment]
it does depend on react but in a shallow way, i think (hope) the bundler will be able to tree shake it away
