### ISSUE TITLE
Doesn't work in IE11 (even when using core-js)

### ISSUE THREAD

**Issue by Jossnaz** [react-spring/zustand#119]
the error is:
>Syntax error

![image](https://user-images.githubusercontent.com/2072058/85792786-acc62480-b6f9-11ea-988b-0c629c1de9c9.png)

I have 

```
import 'core-js';
```
at the top of my file

**Comment by venturalp** [comment]
Hi @Jossnaz, I had the same issue and I found out that I could solve that by using, along with corejs, a different import source for my stores: `import { create } from 'zustand/index.cjs'`

Could you please try that and tell us if it solves?

**Comment by Jossnaz** [comment]
I added, apart from the polyfills, this:
```
import { create } from 'zustand/index.cjs.js
```
and it seems to work.

thanks a lot, would be nice to have it as well in the readme

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
With this solution, How can I resolve type error?

**Comment by venturalp** [comment]
> With this solution, How can I resolve type error?

I guess in the new version of zustand 3+ this problem was solve for good. I didn't update here yet, but I do remember seeing some commit related to cjs modules in this new version. Is it possible for you to update your version?

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@venturalp  What I meant was a typescript error at `import create from 'zustand/index.cjs' code`.
I upgraded to the latest version, but the below error still occurs.

```
Could not find a declaration file for module 'zustand/index.cjs'. '/home/myid/projects/myproject/node_modules/zustand/index.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/zustand` if it exists or add a new declaration (.d.ts) file containing `declare module 'zustand/index.cjs';`
```

**Comment by venturalp** [comment]
> @venturalp What I meant was a typescript error at `import create from 'zustand/index.cjs'` code on VS Code.
> I upgraded to the latest version, but the below error still occurs.
> 
> ```
> Could not find a declaration file for module 'zustand/index.cjs'. '/home/myid/projects/myproject/node_modules/zustand/index.cjs.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/zustand` if it exists or add a new declaration (.d.ts) file containing `declare module 'zustand/index.cjs';`
> ```

Sorry, I forgot to say, I don't think you need to use `/index.cjs` anymore.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
In zustand v3.3.3, Returning the code to `import create from 'zustand'`, I still have to apply the solution: https://github.com/vercel/next.js/issues/13231#issuecomment-711484680

**Comment by dai-shi** [comment]
> What I meant was a typescript error at `import create from 'zustand/index.cjs'` code on VS Code.

Maybe, we can fix it by providing `index.cjs.d.ts`.
