### ISSUE TITLE
synchronous access to state values impossible?

### ISSUE THREAD

**Issue by Jossnaz** [react-spring/zustand#121]
I want to do this:

```
export const [useMyLiteralStore] = create((set: (state:{}) => void) => ({
  literals: '',
  setLiterals: (newLiterals: string) => set((state:{}) => ({ literals: newLiterals })),
}));

const MyReactComp: React.FC<Props> = (Props) => {

  const setLiterals = useMyLiteralStore((state: any) => state.setLiterals);
  const myliterals = useMyLiteralStore((state: any) => state.literals);

  useEffect(() => {
    setLiterals('myTestValue');
console.error("myliterals ", myliterals); //not 'myTestValue' <------- I WANT THIS TO ACTUALLY BE 'myTestValue'
  }, []);
```

is there a way to achieve what I want? I want to have access to myliterals, after setting it, in a synchronous way like shown above.

What I certainly _dont_ want to do, is hand around my global state in function arguments to side step the problem.

**Comment by olavoparno** [comment]
Why don't you async it? async () => {}

**Comment by Jossnaz** [comment]
> Why don't you async it? async () => {}

you mean:
```
  const setLiterals = useLinkScannerStore(async (state: any) => state.setLiterals);
```

once I call it I get:
```
Uncaught TypeError: setLiterals is not a function
```

**Comment by cosmophile** [comment]
You can use `api.getState().literals' after setting it to get the updated value synchronously. Hook returned value will cause a re-render before updating - that's the point of using hooks. The `api` api on the other hand is synchronous.

**Comment by Jossnaz** [comment]
I highly appreciate your comment, I'll look into it

personally, I dont understand why a rerender is required, for the value to update. I'm not saying "technically" i'm saying, why did they decide, that that is a good thing. I get "subscribe my UI to state changes" 100%. Yes. But `setA('foo'); alert(A); //not 'foo'` is honestly, for me personally, very bad. Makes things unnecessary complicated if you have, say, 2 states that depend on each other somehow. Like you have state variables, that should help you with dealing with state, bummer: they are constantly invalid. I to this day, don't understand how this is ever a good thing.

**Comment by cosmophile** [comment]
I know what you're saying. Hooks and Effects particularly require a shift in approach as to be counterintuitive to linear functional programming. But rendering is not linear and that's why it's better to look at functions that use hooks as UI themselves (instead of UI being limited to the JSX they return).

So something like
```
const mylatestState = useMyHook()
```
is not equivalent to just getting your state from the store. It's actually saying something more like:
```
const mylatestState = theStateThatIsReflectedInMyUI()
```

If you want the synchronous value thankfully Zustand provides the `api` for that, and I use it all the time to get and set updated values in contexts that don't need a re-render first and should be never be out of sync with the store.

But we also do need a way to sync with the UI, and to access values that match the *renderstate* and not the *storestate*. All that without being able to see the UI. So hooks are good for that. 

Personally I am thankful to move away from all those class components and just have Hooks+Zustand. Even when it doesn't work the first time(s) I eventually find the right hook+api combo that makes my states and their relationship to various components easier to understand and iterate on.

Sorry if I sound like too much of a cheerleader! I just think the more you use it and use hooks where needed and api where needed, you will be able to leave most of the invalid-state issues behind. 👍

**Comment by olavoparno** [comment]
> I know what you're saying. Hooks and Effects particularly require a shift in approach as to be counterintuitive to linear functional programming. But rendering is not linear and that's why it's better to look at functions that use hooks as UI themselves (instead of UI being limited to the JSX they return).
> 
> So something like
> 
> ```
> const mylatestState = useMyHook()
> ```
> 
> is not equivalent to just getting your state from the store. It's actually saying something more like:
> 
> ```
> const mylatestState = theStateThatIsReflectedInMyUI()
> ```
> 
> If you want the synchronous value thankfully Zustand provides the `api` for that, and I use it all the time to get and set updated values in contexts that don't need a re-render first and should be never be out of sync with the store.
> 
> But we also do need a way to sync with the UI, and to access values that match the _renderstate_ and not the _storestate_. All that without being able to see the UI. So hooks are good for that.
> 
> Personally I am thankful to move away from all those class components and just have Hooks+Zustand. Even when it doesn't work the first time(s) I eventually find the right hook+api combo that makes my states and their relationship to various components easier to understand and iterate on.
> 
> Sorry if I sound like too much of a cheerleader! I just think the more you use it and use hooks where needed and api where needed, you will be able to leave most of the invalid-state issues behind.

Well said, mister, I completely misunderstood @Jossnaz question. This is all about hook's lifecycle. This article here explains it very well https://overreacted.io/a-complete-guide-to-useeffect/

**Comment by Jossnaz** [comment]
I think that hits the nail on the head (maybe):

>But we also do need a way to sync with the UI, and to access values that match the renderstate and not the storestate. All that without being able to see the UI. So hooks are good for that.

even though, when do you want to access the renderstate? when you render the values really. I haven't used the renderstate outside of jsx so far.

btw this is probably even better:
```
const mylatestState = theStateThatIsReflectedInTheCurrentRenderCycleInMyUI()
```

btw the article about useRef doesnt work the way I want it to, see my fork here: 
https://codesandbox.io/s/silent-haze-uo3oy

It still keeps a reference to the renderstate, check the console output, so it's not helpful to me, but there is a workaround I have copied from a different discussion:
https://gist.github.com/Jossnaz/70964f80cff4bb2f717fe8f22a7bd7f6

apart from this, or using zustand, I see no solution to solve the problem I have? 
e.g. setA('foo'); alert(A) //not foo

btw the example i was looking at that made use of useEffect seem plain _horrible_ to me, the anti pattern.

I'm talking about this link:

https://www.robinwieruch.de/react-hooks-fetch-data

this is bad advice, don't follow what he recommends there _ever_ unless you like pain.

I'll copy paste what I mean:

```
  useEffect(() => {
    const fetchData = async () => {
      setIsError(false);
      setIsLoading(true);
 
      try {
        const result = await axios(url);
        setData(result.data);
      } catch (error) {
        setIsError(true);
      }
 
      setIsLoading(false);
    };
 
    fetchData();
  }, [url]);
```

welcome to the pit of hell of timing react lifecycles.

it's back to spaghetti code like this, and setIsError() is called in a new render cycle.

I did exactly like they did in this example, and it caused me only to shake my head and go "what a pile of bs"

In some cases, you want, on button press, load an url

but you most likely dont ALWAYS ALWAYS want to load when the URL changes.

What if, you have one button that loads all data from DB, like "load last state of user when he was on this page, including results"
well, in that case you want to set URL, but the results, you dont load via axios but from the stored state in the DB.

Well, what now? because once you set the URL it will run that code. Now you have to go refactor all sorts of things, and when you do that, all the access to `url` inside of `useEffect` becomes wrong, because `url` outside of `useEffect ... [url])` will be the wrong value. 

another example: lets say, in case of error in above example, you want to reset the URL to empty string. E.g. `setUrl('')` in case of error. Well? in the example of above, that means, the code is executed twice. How comes a super simple code, now makes you do gymnastics in your head? not necessary.

But all of that is "easy" to solve if the component is easy. But go and write a complex component, and then realize "oh dang all of the sudden the useEffects cause me timing problems"

hooks are the only reason I am using react btw, otherwise I wouldnt have used react at all. But they still have screwed it up somehow but well.

Sorry for the rant, I highly appreciate both of your input.
