### ISSUE TITLE
using zustand between different react 'widgets', won't work?

### ISSUE THREAD

**Issue by Jossnaz** [react-spring/zustand#122]
I'm doing something like this:

```
let root_careers = document.getElementById('react-careers');
if (root_careers) {
  render(
      <Careers/>
      , root_careers);
}

let root_news_events = document.getElementById('react-news-nav');
if (root_news_events) {
  render(
      <NewsEventsNav/>
      , root_news_events);
```

I tried sharing state via zustand between both, but it doesnt seem to work, they have different states. Is there a way to bridge between the two?

**Comment by cosmophile** [comment]
Where is the state declared? State sharing is the main reason to use zustand, so it should work if declared and imported properly.

**Comment by olavoparno** [comment]
> I'm doing something like this:
> 
> ```
> let root_careers = document.getElementById('react-careers');
> if (root_careers) {
>   render(
>       <Careers/>
>       , root_careers);
> }
> 
> let root_news_events = document.getElementById('react-news-nav');
> if (root_news_events) {
>   render(
>       <NewsEventsNav/>
>       , root_news_events);
> ```
> 
> I tried sharing state via zustand between both, but it doesnt seem to work, they have different states. Is there a way to bridge between the two?

share with us your state/store declaration and call in your components so that we can better understand your scenario.

**Comment by Jossnaz** [comment]
ah, I guess that's the pitfall

I was "cleaning up" my project and put the zustand into a single file called useModalStore like so

`useModalStore.tsx`
```
import { create } from "zustand/index.cjs.js";


export const [useModalStore] = create((set: (state:{}) => void) => ({
  is_a_modal_open_already: false,
  setIsModalOpenAlready: (is_open: boolean) => set((state:{}) => ({ is_a_modal_open_already: is_open })),
}));
```

```
import { useModalStore } from "./useModalStore.tsx";

export const MyModal: React.FC<Props> = (Props) => {
  const is_a_modal_open_already = useModalStore((state: any) => state.is_a_modal_open_already);
  const setIsModalOpenAlready = useModalStore((state: any) => state.setIsModalOpenAlready);
```

**Comment by Jossnaz** [comment]
I think the problem was that I expected it to synchronous and it wasnt.
