### ISSUE TITLE
Selectors defined outside of a render function do not always return the associated store value

### ISSUE THREAD

**Issue by andrew-me** [react-spring/zustand#123]
I'm having a problem where store values output via a custom hook do not all have the values from the current store. Some have values from the previous store. Here's a brief explanation, I've also pasted more complete code at the end. Appreciate your help!

The crux of the issue is that if I have my selectors in an object useStore(selectors.blah), values from the store are incorrect. If I do this useStore(state => state.blah) there's no problem. More info:

I've grouped my selectors like this (living in a module with the store):

```
export const selectors = {
  status: (state) => state.status,
  profile: (state) => state.profile,
};
```

And use them like this in a custom hook in a separate module

```
  const status = useStore(selectors.status);
  const profile = useStore(selectors.profile);

```

A login and a logout button change store status and profile together from

```
{ status: statusType.LOGGED_OUT, groups: [], profile: null }
```

to

```
{
      status: statusType.LOGGED_IN,
      profile: {
        familyName: 'bob',
      },
    }
```

The values output in the custom hook are not what I was expecting. status has the current value of the store (statusType.LOGGED_IN), profile has the previous value of the store (null). Odd!

If instead I do this in the custom hook

```
  const status = useStore((state) => state.status);
  const profile = useStore(state => state.profile);
```

All is well. status and profile values have the current values of the store on every render

Here's some more complete code:

------

Custom hook

```
import { useStore, selectors, mutators, statusType } from './store';

export function useCustom() {
  const status = useStore(selectors.status);
  const profile = useStore(selectors.profile);

  const login = useStore(mutators.login);
  const logout = useStore(mutators.logout);

  // these do not match the current version of the store on every render
  console.log('profile', profile); // null
  console.log('status', status); // statusType.LOGGED_IN

  switch (status) {
    case statusType.LOGGED_IN:
      return {
        status: statusType.LOGGED_IN,
        isLoggedIn: true,
        profile,
        logout,
      };
    case statusType.LOGGED_OUT:
      return {
        status: statusType.LOGGED_OUT,
        isLoggedIn: false,
        profile,
        login,
      };
    default:
      return {};
  }
}

```
store

```
import create from 'zustand';

export const statusType = {
  LOADING: 'loading',
  LOGGED_IN: 'logged_in',
  LOGGED_OUT: 'logged_out',
};

export const [useStore, store] = create((set) => ({
  status: statusType.LOADING,
  profile: null,
  login: async () => {
    set({
      status: statusType.LOGGED_IN,
      profile: {
        familyName: 'bob',
      },
    });
  },
  logout: async () => {
    set({ status: statusType.LOGGED_OUT, groups: [], profile: null });
  },
}));

if (typeof window !== 'undefined') {
  init();
}

async function init() {
  store.setState({
    status: statusType.LOGGED_IN,
    profile: {
      familyName: 'bob',
    },
  });
}

export const selectors = {
  status: (state) => state.status,
  profile: (state) => state.profile,
};

export const mutators = {
  login: (state) => state.login,
  logout: (state) => state.logout,
};

```

**Comment by cosmophile** [comment]
When I use your custom hook like so in a component, it works fine?
```
export default function App() {
  const mystate = useCustom();
  return (
    <div className="App">
      {!mystate.isLoggedIn ? (
        <button onClick={mystate.login}>Log in</button>
      ) : (
        <button onClick={mystate.logout}>Log out</button>
      )}
    </div>
  );
}

```
You can check it out here: https://codesandbox.io/s/strange-mayer-j2t76?file=/src/App.js

If that's not what you're talking about, feel free to add code to the sandbox that demonstrates your error.

**Comment by andrew-me** [comment]
Ah, apologies I thought I'd checked it thoroughly. You're right the code works fine.
I've updated it to have the error I'm seeing. Right now it requires Formik to see the error. I might try and simplify it later to get the error without the extra library.

Here's the sandbox: [https://codesandbox.io/s/nice-lake-kym1p?file=/src/App.js](https://codesandbox.io/s/nice-lake-kym1p?file=/src/App.js)

I added:
- A small formik form with just a button (I got the error with some form fields as well)
- hasFamilyName: !!profile.familyName on line 23 of App.js

Changing to:

```
 const status = useStore(state => state.status);
  const profile = useStore(state => state.profile);
```

Clears the error

**Comment by cosmophile** [comment]
H'm, maybe someone more knowledgeable will be along in a minute to resolve the issue. Meanwhile, when I just add a check to your profile access code (`hasFamilyName: profile && !!profile.familyName` and `<p>{mystate.profile && mystate.profile.familyName}</p>`, the code starts working again. So I reckon this is an issue of custom hook firing before the login hook has properly set the state. 

Sorry am not familiar with Formik so I'm only seeing what the console is logging, but it's rendering the UI *6 times* after clicking log in, *before* the state is set to the user profile object! So it seems like a Formik issue to me. Sorry can't be of more help!

**Comment by acd02** [comment]
Hello @andrew-me,

I don't really understand the rationale behind the `useCustom` function, looks like all it does is returning your store, it seems like it's only adding an unnecessary layer of complexity.

You could simply use your store as is and it works fine, see this [codesandbox](https://codesandbox.io/s/adoring-rain-j5sit?file=/src/App.js).

**Comment by andrew-me** [comment]
Hi @acd02, 
Our actual codebase is more complex, this is an example of how we were considering using Zustand.
It doesn't seem unusual to use custom hooks to hide a store away.
We can of course re-architect, and will do for now. I wanted to share the issue I have in case others come across it.

**Comment by dai-shi** [comment]
Would somebody help understanding what the current status of this issue?

**Comment by dai-shi** [comment]
@andrew-me Hi, custom hooks to hide a store are totally valid, and grouping selector is nice too (especially because it provides stable selectors).
I hope there's no issue in zustand, but please confirm with the latest version.

Please feel free to reopen this if you still see issues, or file a new issue.

**Comment by andrew-me** [comment]
Hey @dai-shi ,

Thanks for your comments on this and your recent work on Zustand! And apologies for the late reply, I've been stacked at work for a while.

This issue definitely isn't blocking me, but I have tried with the latest version of Zustand and I still see the same issue.
It may well be an issue with formik though, so no need to re-open I think. For anyone that sees a similar issue here's a sandbox with version 3 of Zustand:

https://codesandbox.io/s/cocky-snyder-ndhjk 
It's simplified a bit from the previous sand box

To reproduce open the console then:

1) Click Log out
2) Click Log in
3) See an error in the console 'Cannot read property 'familyName' of null'
4) See also in the console that profile is not null in the store, but that the selector for profile returns null

Two ways to resolve the issue:

1) Remove formik, and just have a button with onClick={mystate.login}
(note this is a very much simplified implementation with formik, I did have a fuller version with a field for familyName but removed that to isolate the issue)
OR
2) Remove the two selectors on lines 6 and 7 inside of the App component

**Comment by dai-shi** [comment]
@andrew-me Thanks for the repro. This is certainly an interesting problem. I guess Formik triggers re-render before Zustand does. Let me re-open this to investigate further.

**Comment by dai-shi** [comment]
The issue is reproducible with delayed update without Formik.
```jsx
        <button onClick={() => {
          forceUpdate();
          setTimeout(() => {
            mystate.login();
          }, 1);
        }}>login</button>
```

**Comment by andrew-me** [comment]
Nice one. Thanks dai-shi!

**Comment by TkDodo** [comment]
Thanks for fixing this - coincidentally, we had an issue filed similar to this one today, where a useEffect updates the state while an async request is in-flight, and then the async request updates the store with outdated data (or so). We also extract selectors to stable functions.

Updating from 3.1.0 to 3.1.1 fixed the issue for us as well, so thank you for taking the time to address this issue @dai-shi 👍
