### ISSUE TITLE
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

### ISSUE THREAD

**Issue by Iixianjie** [react-spring/zustand#127]
if devtools are not used, application will crash after build

```js
export default function creator(...args) {
  // if (process.env.NODE_ENV === 'development') {
  //   return create(devtools(...args));
  //  }
  
  create(...args); 
}
```

![image](https://user-images.githubusercontent.com/34636376/87742448-53917280-c819-11ea-948f-a3cf353218d5.png)

**Comment by dai-shi** [comment]
Can you reproduce the issue with v3?

**Comment by dai-shi** [comment]
Closing this as stale. Feel free to reopen if it's reproducible.

**Comment by mitjnextt** [comment]
Have anyone resolved it?

**Comment by dai-shi** [comment]
@mitjnextt can you make a repro with codesandbox?
