### ISSUE TITLE
How can I get a value from store a in store b

### ISSUE THREAD

**Issue by MRSTIGLITZ** [react-spring/zustand#134]
Im getting an error (Invalid hook call. Hooks can only be called inside of the body of a function component
) when trying to access a value from another store.

Thanks

**Comment by drcmda** [comment]
can i see your code? 

all you need to do is:

```jsx
const foo = useFooStore(state => state.foo)
const bar = useBarStore(state => state.bar[foo])
```

**Comment by MRSTIGLITZ** [comment]
Thanks for your quick response. I was trying to import one store into another store but I refactor my code and with the example for the async actions I was able to get a solution.
Just one question, Im more used to redux style so Is this the correct approach to dispatch methods and state?
```
const createImmer = () => {
  const immer = config => (set, get, apis) => config(fn => set(produce(fn)), get, apis);
  return immer;
};

const fetchOrganization = async set => {
  try {
    const response = await api.get('portal/dashboard/organizationinfo');
    const { data } = response;
    set(_ => ({ organization: data }));
  } catch (error) {
    console.log(error);
  }
};

const [useOrgStore] = create(
  devtools(
    createImmer()(set => ({
      organization: {},
      setOrganization: () => fetchOrganization(set),
    })),
  ),
);

export default useOrgStore; 
```

**Comment by drcmda** [comment]
there's a clean cut example on the github front for redux reducers, action types and so on. yours doesnt really strike me as redux style. but zustand is whatever you like it to be.
