### ISSUE TITLE
Setting initial state and updating in an interval

### ISSUE THREAD

**Issue by kickbk** [react-spring/zustand#140]
Sorry for the newb question here. I'm trying to store the current time with Zustand and update it every second without re-rendering the app.

Currently I have:

```
...
import create from 'zustand';

const [useStore] = create((set) => ({
  currentDateTime: undefined,
  setCurrentDateTime: () => set((state) => ({ currentDateTime: new Date() })),
}));

export default function App() {
  const { currentDateTime, setCurrentDateTime } = useStore();
  useEffect(() => {
    const secondsTimer = setInterval(() => {
      setCurrentDateTime();
    }, 1000);
    return () => clearInterval(secondsTimer);
  }, [setCurrentDateTime]);

  console.log('Setting the time');
  ...
```

I am seeing the console log every second, which means it is re-rendering.
What am I doing wrong here?

**Comment by kickbk** [comment]
Never mind, figured I actually have to have the state updating in this case every second to display the current time? (correct me if I'm wrong)

**Comment by dai-shi** [comment]
I guess it's because your component reads `currentDateTime` from store.
```js
const setCurrentDateTime = useStore(state => state.setCurrentDateTime);
```
should work?

**Comment by kickbk** [comment]
@dai-shi I gave this a try:

```
const { currentDateTime } = useStore();

  const setCurrentDateTime = useStore((state) => state.setCurrentDateTime);

  useEffect(() => {
    const secondsTimer = setInterval(() => {
      setCurrentDateTime();
    }, 1000);
    return () => clearInterval(secondsTimer);
  }, [setCurrentDateTime]);

  console.log('Setting the time', currentDateTime);
```

Is that what you meant?
I am still getting a console log every second. I am not sure if that matters, but I have a feeling it's re-rendering the component every second. If I include this component in one of the top level components, isn't it going to re-render every component on the screen? If so, that would be bad.

**Comment by dai-shi** [comment]
Can you try removing this line `const { currentDateTime } = useStore();`

**Comment by kickbk** [comment]
But then how do I print the current time? console.log('Setting the time', currentDateTime); will obviously not work because currentDateTime is undefined, and the render (I omitted it above) will not show it either.

**Comment by dai-shi** [comment]
Sorry, if my comment was ambiguous.

Is your problem solved now?

**Comment by kickbk** [comment]
@dai-shi, thanks for your answer. My issue wasn't directly related to Zustand. It has to do with manipulating a component without causing a re-render. I did some research on it and [found a solution](https://stackoverflow.com/a/63406954/2752719).

**Comment by dai-shi** [comment]
You could use `useRef`, but if you just need to get the latest value from the store without re-render, you could do this.

```js
import create from 'zustand';

const [useStore, api] = create((set) => ({
  currentDateTime: undefined,
  setCurrentDateTime: () => set((state) => ({ currentDateTime: new Date() })),
}));

export default function App() {
  const setCurrentDateTime = useStore((state) => state.setCurrentDateTime);
  useEffect(() => {
    const secondsTimer = setInterval(() => {
      setCurrentDateTime();
    }, 1000);
    return () => clearInterval(secondsTimer);
  }, [setCurrentDateTime]);

  const { currentDateTime } = api.getState();
  console.log('Setting the time', currentDateTime);
```

I'm not sure if this is good in your use case. It depends on the requirement, but maybe I wouldn't even use `useEffect`.

```js
import create from 'zustand';

const [useStore, api] = create((set) => ({
  currentDateTime: undefined,
  setCurrentDateTime: () => set((state) => ({ currentDateTime: new Date() })),
}));

setInterval(() => {
  const { setCurrentDateTime } = api.getState();
  setCurrentDateTime();
}, 1000);
```

**Comment by kickbk** [comment]
Nice. The only problem is that I also need to display the updating value on the screen (for instance, with `return <Text>{currentDateTime.toLocaleString()}</Text>`). I'm ok with running the timer without the useEffect, as you suggested. It's indeed cleaner. Just need to show the updating time without re-rendering. Any suggestions?

**Comment by dai-shi** [comment]
You need to re-render to update UI. What you are asking is probably re-render only small part of the component tree. Just put `useStore` where you want to re-render, not the top App.

**Comment by dai-shi** [comment]
Does it solve your problem? Let me close this for now. Feel free to reopen.

**Comment by kickbk** [comment]
Thanks @dai-shi . Yes, it helped a lot.
