### ISSUE TITLE
Remove actions from store for simpler API

### ISSUE THREAD

**Issue by timkindberg** [react-spring/zustand#151]
I am realizing I should have shared this idea earlier... now v3 is released so it's a bit late... or is it?

The premise of this idea is that it's always felt a bit odd to keep the actions themselves inside the store. I _guess_ a dev might want to change the actions dynamically but I'd venture to say this is not happening in 99% of use cases.

So... I was playing with an idea of how I might be able to use zustand in a more casual way. I wanted to be able to easily lift my state from a local `useState` to a "global" zustand store. I [tweeted about it here](https://twitter.com/kindberg/status/1293752005169762304). Within that tweet there is a [codesandbox with a playground](https://codesandbox.io/s/easy-global-and-context-state-lifting-tgvb0?file=/src/App.js:960-1228) exploring this idea.

The core idea of the playground is something like this:
```js
// `globalState` uses zustand behind the scenes
const [useName, setName] = globalState('Tim')  // Store a simple literal
const [usePet, setPet] = globalState({ type: 'Cat', name: 'Nacho')  // Or store an object

const App = () => {
  const name = useName()
  const pet = usePet()  // could use a selector here if you want
  return (
    <div>
      // Call the setters from anywhere!
      <button onClick={() => setName('Bob')}>Change Name</button>
      <button onClick={() => setPet({ name: 'Beanie' })}>Change Pet Name</button>
    </div>
  )
}
```

So what did I learn from the idea?

That zustand stores are really about the data inside and subscribing to that data. The actions do not feel like they belong inside, they are just overhead. All that is really needed is exposing the set and get functions.

I realize this is all possible with v3 and you might be tempted to close this because of that reason, but I'm wondering if this mental shift should be more baked into the docs, or code, or both?

This is what I imagine it looking like (using the readme example). FWIW I love how v3 hangs additional methods on the hook, I also came to this conclusion recently.
```js
import create from 'zustand'

const useCount = create(0) // Just provide the state, no actions

// Now, if you want create bespoke actions using the exposed useCount.set
// Side note: I think it should be called useCount.get() to get the state, just shorter and more elegant
const increase = () => useCount.set(state => ({ count: state.count + 1 })),
const reset = () => useCount.set({ count: 0 })

function Counter() {
  const count = useCount()
  return <h1>{count}</h1>
}

function Controls() {
  return <button onClick={increase}>up</button>
}
```

As you can see this simplifies the API greatly! Thoughts??

**Comment by timkindberg** [comment]
Additional idea. The v3 rewrite has me brainstorming!

Maybe it would be better to encourage vanilla store usage even in React and then use a hook "just-in-time" when you need the data within a component? I'll admit the above `useCount.set` access seems a bit odd... so maybe something more like this.

So maybe instead of two `create` methods (one vanilla, one for react), just have one vanilla create and a react hook that takes the vanilla store directly.
```js
import create from 'zustand' // the vanilla create could be zustand's default export
import useStore from 'zustand/hooks'

const countStore = create(0) // Just provide the state, no actions

// Now, if you want create bespoke actions using the exposed useCount.set
// Side note: I think it should be called useCount.get() to get the state, just shorter and more elegant
const increase = () => countStore.set(state => ({ count: state.count + 1 })),
const reset = () => countStore.set({ count: 0 })

function Counter() {
  const count = useStore(countStore)
  return <h1>{count}</h1>
}

function Controls() {
  return <button onClick={increase}>up</button>
}
```

This looks pretty great yeah? `countStore.set` feels better than `useCount.set`

**Comment by drcmda** [comment]
you might wanna talk to @dai-shi ;-) there's something else coming very soon. 

zustands api is more for completely unopinionated usage, nested actions, json patch data, etc. it is great for that because it doesnt assume a greater structure. but it's secret companion - looking at what you write, you'll be very surprised.

**Comment by timkindberg** [comment]
Ok! Very exciting now I'm quite curious. I look forward to hearing from him!

**Comment by dai-shi** [comment]
Well, I understand what you mean and what you probably want.

What we could do with zustand is something like this. How are you comfortable with this?
```js
import create from 'zustand'

// helper create function
const createValue = (initialValue) => {
  const useStore = create(set => ({
    value: initialValue,
    setValue: (update) => set(prev => ({ value: typeof update === 'function' ? update(prev.value) : update })),
  })
  const { setValue } = useStore.getState()
  const selectValue = state => state.value
  const useValue = () => useStore(selectValue)
  return [useValue, setValue]
}

const [useCount, setCount] = createValue(0)
const increase = () => setCount(c => c + 1)
const reset = () => setCount(0)

function Counter() {
  const count = useCount()
  return <h1>{count}</h1>
}

function Controls() {
  return <button onClick={increase}>up</button>
}
```

**Comment by dai-shi** [comment]
> `countStore.set` feels better than `useCount.set`

Now with the vanilla api, we could do this. You may like this pattern better?
```jsx
import create from 'zustand/vanilla'
import create as createHook from 'zustand'

const countStore = create(() => ({
  count: 0,
}))

const increase = () => countStore.setState(prev => ({ ...prev, count: prev.count + 1 }))
const reset = () => countStore.setState({ count: 0 })
const useCount = createHook(countStore)

function Counter() {
  const count = useCount()
  return <h1>{count}</h1>
}

function Controls() {
  return <button onClick={increase}>up</button>
}
```

**Comment by timkindberg** [comment]
Ah yes, thank you. I like your second example best of the two. That is _very_ close to perfect. The only feedback I'd have now for an even more elegant API is:

1. Can we allow values and objects as the param for create? 
- `const countStore = create(0)`
- `const userStore = create({ name: 'Tim', city: 'Cincinnati' })`
- `const toggleStore = create(true)`

2. Can we bypass the need to make the hook before using it? Can zustand export a hook that consumes a vanilla store?
```
import useStore from 'zustand/hooks'
const countStore = vanillaCreate(...)
function Counter() {
  const count = useStore(countStore)
}
```

**Comment by dai-shi** [comment]
1: should be possible. there might be TS issues.
2: technically possible. it's the matter of api design and documentation. Oh no, this would not be possible in v4. We'd need additional wrapper or react-aware store. So, maybe it's not very nice.
cc: @drcmda

**Comment by timkindberg** [comment]
Thanks @dai-shi we can see what @drcmda thinks.

Put another way... now that setting and getting the state is so readily available on both the vanilla store and the hook prototype, it begs the question **"What is the purpose of providing `(set, get)` to the create function at all?"**. And that's the core of the suggestion I'm raising. It strikes me as unnecessary API baggage now. The only reason would be backwards compatibility.

It seems that accepting the function arg within `create` could be removed completely. If we want to "set" we can with `useMyStore.setState` or `vanillaStore.setState`. Same with "get".

**Comment by drcmda** [comment]
the reason is mostly that the state model comes predefined by the applications needs. at work for instance state is a fixed json object that comes in remotely, the server patches changes via json-patch. if the state manager tried to assume structure i wouldnt work for our purposes. the atomic state idea is great, but it's not one thing fits all - it suits different usecases. for that we will unveil a second project soon.

**Comment by dai-shi** [comment]
> i think allowing initialstate without function is fine with me, we can add that in a minor, @dai-shi what do you think?

Oh, I misunderstood the first item. For the create in index.ts, we need to distinguish function and object, so it's technically impossible. For the vanilla create, it's possible, but I'm a bit hesitant to  provide different signatures. (It's already different but it's like overloading.)

**Comment by drcmda** [comment]
oh youre right, the new change. yes, i agree - it would make a mess. () => {} instead of {} isnt that much to ask for tbh.

**Comment by zoontek** [comment]
I'm not really a fan of the `getState`, `setState`, etc prototype methods on `useStore`. The `import create from 'zustand/vanilla'; import createHook from 'zustand';` makes more sense to me.

I also agree about discouraging putting the getters / setters inside the store. Could be nice to se that kind of change in the v4.

Two other things that bugs me too: The need for the store to be an object. I understand it's about selectors, but would it be possible to have an API that handle both?

```ts
const store = createStore(0);

const increment = store.set(prev => prev + 1);
const decrement = store.set(prev => prev - 1);

const useStore = createHook(store, isEqual); // useStore will not accept selectors since the store is not an object
```

And partial state application, which does not play well with `undefined` values.

```ts
type Store = {
  count: number;
  optional?: string;
};

const initialState: Store = {
  count: 0
};

// the function is not useful if we encourage outside getters / setters
const store = create<Store>(() => initialState);

const increment = () =>
  store.setState((prevState) => ({ ...prevState, count: prevState.count + 1 }));

const setOptional = (optional: string) => {
  store.setState({ optional });
};

const resetStore = () => {
  store.setState(initialState);
};

increment();
setOptional("foo");
resetStore();

console.log(store.getState()); // {count: 1, optional: "foo"}
```

**Comment by drcmda** [comment]
the api isnt for most people to use, but the signature is redux compatible and that would in theory allow you to either re-use existing store, or use a zustand store in redux. but most people (99.9%) will use an object state model, hooks and actions. vanilla folks will use it just like they just redux. again, same api. using zustand for atomics imo makes no sense because then you could really just use context, just with the additional nesting cost. but for that case we will have a second project soon that deals with atomic stores properly.

**Comment by timkindberg** [comment]
Thank you for all the consideration and suggestions on how I can use the v3 api. I think I am happy with the below as a compromise, which is possible with existing v3 api.

@zoontek Now that the `setState` (and `getState`) are available on the hook (and vanilla store) I will likely start to prefer to use those instead of adding `actions` to my store structure. And I'll likely just use the hook version, even though it's a bit odd to access the prototype methods it is also convenient enough for me to prefer it.

So instead of this
```js
const useStore = create(set => ({ 
  some: 'state',
  actions: { someAction() { set(...) } }
}))
function App() {
  const { actions } = useStore(s => s.actions)
  actions.someAction()
}
```

I'll be exploring doing this instead 👍 
```js
const useStore = create(() => ({ some: 'state' }))
const someAction = () => userStore.setState(...)
function App() {
  someAction(...) // No required boilerplate, can be called anywhere
}
```

**Comment by MonstraG** [comment]
Decided to use same approach, but also declare a namespace to organize it:
```ts
namespace SomeStore {
  export const useStore = create(() => ({ some: 'state' }))
  export const someAction = () => userStore.setState(...)
}
export default SomeStore;

function App() {
  const some = SomeStore.useStore(state => state.some)
  SomeStore.someAction() // No required boilerplate, can be called anywhere
}
```
