### ISSUE TITLE
Possible to translate a useReducer to Zustand?

### ISSUE THREAD

**Issue by rchrdnsh** [react-spring/zustand#158]
I have a reducer:

```jsx
const reducer = (state, action) => {

  switch (action.change) {
    case 'ROOT' :
      return {
        ...state,
        root: action.value
      }
    case 'QUALITY' :
      return {
        ...state,
        quality: action.value
      }
    case 'EXTENSION' :
      return {
        ...state,
        extension: action.value
      }
    case 'CHORD' :
      return {
        ...state,
        quality: action.value.split(`-`)[0],
        extension: action.value.split(`-`)[1]
      }
    case 'RESET' :
      return { 
        ...state,
        root: '',
        quality: '',
        extension: ''
      }
    default :
      return state
  }
}
```

...which is used in a react component utilizing the `useReducer` hook, like so:

```jsx
const [{ root, quality, extension }, dispatch] = useReducer(
    reducer,
    {
      root: ( props.root || '' ),
      quality: ( props.quality || '' ),
      extension: ( props.extension || '' )
    }
  )

  const handleRootChange = event =>
    dispatch({ change: 'ROOT', value: event.target.value })

  const handleQualityChange = event =>
    dispatch({ change: 'QUALITY', value: event.target.value })

  const handleExtensionChange = event =>
    dispatch({ change: 'EXTENSION', value: event.target.value })

  const handleChordChange = event => {
    dispatch({ change: 'CHORD', value: event.target.value })
  }

  const handleReset = event =>
    dispatch({ change: 'RESET'})

  const notes = `${root}-${quality}-${extension}`
```

...soooo, can something like this be achieved using Zustand in a simper way?

**Comment by timkindberg** [comment]
If you wanted to stick with a reducer:
```js
// Create Store
const useStore = create(set => ({
  root: '',
  quality: '',
  extension: ''
  dispatch: args => set(state => reducer(state, args)),
}))

// Usage in Component
const dispatch = useStore(state => state.dispatch)
dispatch({ change: 'ROOT', value: event.target.value })
```

If you wanted to do it more traditional zustand:
```js
const useStore = create(set => ({ 
  root: '',
  quality: '',
  extension: '',
  actions: {
    changeRoot: root => set({ root }),
    changeQuality: quality => set({ quality }),
    changeExt: extension => set({ extension }),
    changeChord: chord => set({
        quality: chord.split(`-`)[0],
        extension: chord.split(`-`)[1]
    }),
    reset: () => set({ 
      root: '',
      quality: '',
      extension: ''
    })
  }
}))

// Usage
const root = useStore(s => s.root)
const actions = useStore(s => s.actions)
actions.changeRoot(...)
```

**Comment by rchrdnsh** [comment]
hmmmm...so I'm a little confused as to how to implement this:

```jsx
  const root = useStore(state => state.root)
  const quality = useStore(state => state.quality)
  const extension = useStore(state => state.extension)
  const actions = useStore(state => state.actions)

  const handleRootChange = event => actions.changeRoot(event.target.value)
  const handleQualityChange = event => actions.changeQuality(event.target.value)
  const handleExtensionChange = event => actions.changeExtension(event.target.value)
  const handleChordChange = event => actions.changeChord(event.target.value)
  const handleReset = event => actions.reset()
```

...but everything is returning as null, so I guess I'm a little bit confused as to how to implement it in the component itself...

**Comment by timkindberg** [comment]
If you reproduce your issue in codesandbox.io I'll help you debug.

**Comment by rchrdnsh** [comment]
hmmmmm...very odd...

I made a code sandbox:

https://codesandbox.io/s/zustand-vs-usereducer-vf10u?file=/src/Chords.js

...and it's working perfectly fine, but in my Gatsby app the state is `null null null` for each of the three state values I'm setting...didn't change anything, just copied and pasted the code from my project...🤔

**Comment by timkindberg** [comment]
What version of zustand in your project? The api JUST changed in v3 from:
```
const [useStore] = create(...)
```
to
```
const useStore = create(...)
```

**Comment by rchrdnsh** [comment]
`"zustand": "^3.0.1"` is the version where I am running into this issue...

**Comment by drcmda** [comment]
im not sure what this is

```jsx
  const root = useStore((state) => props.root || state.root);
```

the selector is suppoed to pick a piece of state, it isn't supposed to just return any random value from outside.

**Comment by rchrdnsh** [comment]
Hi @drcmda :-)

Being able to get state values from either the reducer or the props of the component is for the component API, where the content author can choose whether to input values for these pieces of state or let them be blank by default, for different use cases.

For example:

In this use case all state is left blank because all aspects of the component are being utilized:

<img width="1338" alt="Screen Shot 2020-08-19 at 9 57 24 AM" src="https://user-images.githubusercontent.com/7884263/90666643-89ec5400-e202-11ea-97c4-53e3ffc41208.png">

with the component looking like this:

```jsx
<Chords
  tool
  resetbutton
  chordselector
/>
```

...where the author defines the use case with `tool` then whether or not to show pieces of the UI with `resetbutton` and `chordselector`.

In other use cases, however, like inline in an MDX article the state needs to be set to limit what it can be for that particular situation (not fully styled and laid out properly yet):

<img width="1162" alt="Screen Shot 2020-08-19 at 9 58 15 AM" src="https://user-images.githubusercontent.com/7884263/90666849-d8015780-e202-11ea-843b-ef18e267dc4f.png">

with the component looking like this:

```jsx
<Chords
  article
  root={'c'}
  quality={'minor'}
  extension={'triad'}
/>
```

...in this particular use case the author is writing about minor triads and allows the user to only change the root note to see all the minor triads available, but not to change the values of quality and extension for the chords. The author also defines a starting value for the root to show the reader an example of what this component is doing. The use case is defined as `article` and the `resetbutton` and `chordselector` are not present, as they are not needed in this instance of the component.

So I need the component to be able to support these two (and maybe more in the future) use cases in regards to setting default values for state on a per component basis.

**Comment by dai-shi** [comment]
@rchrdnsh 

> it's working perfectly fine, but in my Gatsby app the state is null null null

Sounds really hard to track down. Is it possible for you to create a **minimal** repro with Gatsby?

**Comment by dai-shi** [comment]
Closing this as stale. Please file a new issue with a repro.
We would like to solve issues if there are any with Gatsby.
