### ISSUE TITLE
please highlight breaking changes when migrating from v2 to v3 (( thank you )).

### ISSUE THREAD

**Issue by a-eid** [react-spring/zustand#159]
so far I was able to identify 1 breaking change in the lib api.

```js
const [useStore, storeApi] = create(...)
storeApi.setState(...)
```

```js
const useStore = create(...)
useStore.setState(...)
```

**Comment by drcmda** [comment]
it's in the release tag https://github.com/react-spring/zustand/releases/tag/v3.0.0

there are no breaking changes in this release. but v4 will cut off the tuple api.

**Comment by uzairfaisal** [comment]
Actually, I'd like to highlight a breaking change. When using `devtools`, the `set` function which saves the partial object to the state would previously accept the `name` of the action as the 2nd param. Now, the 2nd param is changed to whether the partial object should overwrite the state or not - and any previous `name` param being passed to the `set(...)` would result in the state being overwritten in `3.x` whereas this was not the behaviour in `2.x`.

This is highlighted here:
https://github.com/pmndrs/zustand/blob/master/src/middleware.ts#L33

Unless I missed something already mentioned before/somewhere else, please highlight this as a breaking change from 2 -> 3 so it's clear for all. This tripped our upgrade to `3.x`.

**Comment by dai-shi** [comment]
@uzairfaisal 
Hi, thanks for trying. As far as I remember, that's something we fixed in v3. #77 
Does devtools in v2 work at all for you?

**Comment by uzairfaisal** [comment]
> @uzairfaisal
> Hi, thanks for trying. As far as I remember, that's something we fixed in v3. #77
> Does devtools in v2 work at all for you?

@dai-shi the fix you're referring to is adding the `replace` argument for the `set(...)` (when using `devtools`), but instead you added it as the 2nd param but that breaks the API from v2 code.

Afaik, devtools _should_ works for us in v2 (CC: @timkindberg) though I haven't explicitly checked this. The very same code example that should work in v2 in that post you linked would fail in v3:

```JS
const [useStore] = create(devtools(set => ({
  count: 1,
  inc: () => set(state => ({ count: state.count + 1 }), 'inc'), // in v3, the 2nd param is for replace and in v2, the 2nd param is for name
  dec: () => set(state => ({ count: state.count - 1 }), 'dec') // same here
})))
```

It should instead be

```JS
const [useStore] = create(devtools(set => ({
  count: 1,
  inc: () => set(state => ({ count: state.count + 1 }), false, 'inc'), // notice the 2nd param change
  dec: () => set(state => ({ count: state.count - 1 }), false, 'dec') // same here
})))
```

If I don't pass `false` (or falsey) as the 2nd argument, the `inc` + `dec` attributes will be lost in the store. This means that v2 code using `devtools` *does* need to be changed (ie. breaking change). Hope that helps narrow this down.

**Comment by dai-shi** [comment]
That was a huge misunderstanding of mine. Thanks for noting.
I added a note in v3.0.2 release which has the change.
Please suggest better description if you have any.
https://github.com/pmndrs/zustand/releases/tag/v3.0.2

**Comment by MarkAPhillips** [comment]
Please note there is still in issue in relation to Typescript which has been mentioned but thought I would highlight it again as it still expects 1-2 arguments and not 3 as above if you use the SetState type

**Comment by dai-shi** [comment]
@MarkAPhillips TS support is changed and should be improved in v4. Please open a new issue with a reproduction.

**Comment by MarkAPhillips** [comment]
@dai-shi  thanks - I realise the issue now and more relates to documentation - that is you can use the NamedSet<T> type if using devtools - which I determined from your updates - maybe this is something to consider when releasing the next version
