### ISSUE TITLE
How to extract common logic and reuse it in multiple store

### ISSUE THREAD

**Issue by csr632** [react-spring/zustand#161]
How to extract common logic from store and reuse it in multiple store (or for multiple times)?

For example, we often need to track the loading state and error state of requsts. How to reuse this logic?

Here is some [suggestion from redux community](https://stackoverflow.com/q/50169002). In the react hook world, we have [swr](https://github.com/vercel/swr).

If zustand have solution for this, we should put it in the documentation!

**Comment by dai-shi** [comment]
store logic in zustand is just a function. So, you could define a common function. There's also middleware. Do you have any suggestion?

Is the example something like this?
```js
const useStore = create(set => {
  result: null,
  loading: false,
  error: null,
  fetch: async url => {
    try {
      set({ loading: true })
      const result = await (await fetch(url)).json()
      set({ loading: false, result })
    } catch(error) {
      set({ loading: false, error })
    }
  },
});
```

**Comment by csr632** [comment]
scopedSet + immer looks perfect to me!
I will try it with typescript, and see if type inference works perfectly too.

**Comment by dai-shi** [comment]
@csr632 Any updates?

**Comment by csr632** [comment]
@dai-shi 
Current zustand API is not friendly to ts, see https://github.com/react-spring/zustand/issues/95#issuecomment-685821630

**Comment by dai-shi** [comment]
If it's about ts friendliness, maybe, we should open a new issue for discussion then, instead of using the old issue, and close this issue?

**Comment by dai-shi** [comment]
Or, maybe just close this and reopen the other one because it has good discussion there.

**Comment by DalderupMaurice** [comment]
> How about this?
> 
> ```js
> const createFetchStore = (fetchActionName, baseUrl) => create(set => {
>   result: null,
>   loading: false,
>   error: null,
>   [fetchActionName]: async (id)=> {
>     try {
>       set({ loading: true })
>       const result = await (await fetch(`${baseUrl}/${id}`)).json()
>       set({ loading: false, result })
>     } catch(error) {
>       set({ loading: false, error })
>     }
>   },
> });
> ```

I'd like to add to this solution that it's not always an API call that requires you to keep track of the loading state.
What if you're using your own service or another NPM library that executes code asynchronously.
With this, you cannot use your proposed solution.

For ex:
```js
const useWalletStore = create(set => {
  result: null,
  loading: false,
  error: null,
  fetch: async url => {
    try {
      set({ loading: true })
      const result = await MyWalletService.generateWallet();
      set({ loading: false, result })
    } catch(error) {
      set({ loading: false, error })
    }
  },
});

const useChartStore = create(set => {
  result: null,
  loading: false,
  error: null,
  fetch: async url => {
    try {
      set({ loading: true })
      const result = await MyWalletService.getBalance();
      const chartData = await ChartService.generate(result);
      set({ loading: false, chartData })
    } catch(error) {
      set({ loading: false, error })
    }
  },
});
```

in this example, you see the usage of different services that each use async operations, but there is no way to remove the duplicated code of the loading state.

It'd be nice if there was some kind of middleware to automatically add the loading and error property and set the loading state before/after the action is done or if it fails, to set the error property and loading state as well.

**Comment by dai-shi** [comment]
But, then you could accept custom `fetchFunc` instead of `baseUrl`?

```js
const createFetchStore = (fetchActionName, fetchFunc) => create(set => {
  result: null,
  loading: false,
  error: null,
  [fetchActionName]: async (id)=> {
    try {
      set({ loading: true })
      const result = await fetchFunc(id)
      set({ loading: false, result })
    } catch(error) {
      set({ loading: false, error })
    }
  },
});
```

You could extract the logic in another way. Someone can try it as middleware.

**Comment by DalderupMaurice** [comment]
> But, then you could accept custom `fetchFunc` instead of `baseUrl`?
> 
> ```js
> const createFetchStore = (fetchActionName, fetchFunc) => create(set => {
>   result: null,
>   loading: false,
>   error: null,
>   [fetchActionName]: async (id)=> {
>     try {
>       set({ loading: true })
>       const result = await fetchFunc(id)
>       set({ loading: false, result })
>     } catch(error) {
>       set({ loading: false, error })
>     }
>   },
> });
> ```
> 
> You could extract the logic in another way. Someone can try it as middleware.

This would mean you'd have to pass the service name, fetchFunc, or whatever you're calling from your react component, but there are a couple of problems with that:
- An action shouldn't be limited to a 1-off method call (which is the case here) 
- Ideally, the react component shouldn't know anything about whatever you're doing in the action (separation of concerns). 
- When you change the function name/service name or whatever, the action call breaks (if you're using strings to reference what method should be called)

A middleware would be the way to go IMO. 
I could create one (I think) but I'm not comfortable with creating the typing of it.

**Comment by dai-shi** [comment]
> not comfortable with creating the typing of it.

Yeah, middleware is hard for typing. I'd avoid it if possible. A store create helper would be easier.

Just in case, your example would like this with the helper:
```ts
const useWalletStore = createFetchStore('fetch', async (url) => {
  const result = await MyWalletService.generateWallet();
  return result;
});

import ChartJS from "chart-js";

const useChartStore = createFetchStore('fetch', async (url) => {
  const result = await MyWalletService.getBalance();
  const chartData = await ChartJS.generate(result); // this is dummy code, just as an example
  return chartData;
});
```

**Comment by DalderupMaurice** [comment]
> > not comfortable with creating the typing of it.
> 
> Yeah, middleware is hard for typing. I'd avoid it if possible. A store create helper would be easier.
> 
> Just in case, your example would like this with the helper:
> 
> ```ts
> const useWalletStore = createFetchStore('fetch', async (url) => {
>   const result = await MyWalletService.generateWallet();
>   return result;
> });
> 
> import ChartJS from "chart-js";
> 
> const useChartStore = createFetchStore('fetch', async (url) => {
>   const result = await MyWalletService.getBalance();
>   const chartData = await ChartJS.generate(result); // this is dummy code, just as an example
>   return chartData;
> });
> ```

I get your approach and it's a good one, but I still miss a piece of the puzzle.
In your scenario, you create individual stores for each individual action which makes the "get" method quite useless if you'd like to access values from other stores.

For example (no actual code, just made something up):
```js 
const useSettingStore = create(set => {
  currency: "EURO",
  decimales: 2,
  hidden: false
  setCurrency: newCurrency => set({ currency: newCurrency  }),
  .....
});

const useChartStore = createFetchStore('fetchChartData', async (decimals, currency, hidden, account, tokens, balances) => {
  if(hidden) return "****"; // <-- Cannot get this setting using get().hidden;
  return ChartService.getChart(decimals, currency, account); // <-- Only way to get the params is by passing it down...
});

// .. other async stores made by createFetchStore (useTokenStore, useBalancesStore, useAccountsStore, ....)

// Cluttered React Component
const WalletComponent = () => {
   const { currency, decimals, hidden } = useSettingStore(); // Settings store
   const { tokens } = useTokensStore(); // async action store create through "createFetchStore"
   const { balances } = useBalancesStore(); // async action store create through "createFetchStore"
   const { account } = useAccountStore(); // async action store create through "createFetchStore"
   const { chartData, fetchChartData } = useChartStore(); // async action store create through "createFetchStore"
   // Any other "async" variable needed (created using createFetchStore) would add a line as they are individual stores

  fetchChartData(decimals, currency, hidden, account, tokens, balances);   
}
```

In the example above, you cannot use `get().xxxx` and instead have to bloat your react component with hooks to retrieve this piece of data and pass it down to the action call.

Of course, this isn't a big problem in a small application, but it does become a problem when you're at a point where you have to pass down 1-3 of these values (Currency, Language, Network, any kind of setting, account data, or other metadata...) to each action you're calling, which clutters the codes massively in basically ALL of the components where you need some kind of data.

I've also tried to create a middleware for this issue, but I figured out that middlewares are just hooks to perform before and/or after the `get`, `set`, and/or `api` params. I couldn't figure out how to add a variable to the store inside a middleware and run it before and after the execution of the action instead.

**Comment by dai-shi** [comment]
> if you'd like to access values from other stores.

In general, I would recommend to create a single store unless multiple stores are totally isolated.

In a single store scenario, if we need to extract common logic, we might extract store creator functions partially.

```js
const createFetcher = (prefix, fetchFunc) => (set, get) => ({
  [prefix + 'result']: null,
  [prefix + 'loading']: false,
  [prefix + 'error']: null,
  [prefix + 'fetch']: async (arg)=> {
    try {
      set({ [prefix + 'loading']: true })
      const result = await fetchFunc(arg, { set, get })
      set({ [prefix + 'loading']: false, [prefix + 'result']: result })
    } catch(error) {
      set({ [prefix + 'loading']: false, [prefix + 'error']: error })
    }
  },
});

const fooFetcher = ('foo', async (id, { set, get }) => { ... });
const barFetcher = ('bar', async (id, { set, get }) => { ... });

const useStore = create((set, get) => ({
  ...fooFetcher(set, get),
  ...barFetcher(set, get),
}))
```

(Note: I never actually tried this approach...)

**Comment by DalderupMaurice** [comment]
> > if you'd like to access values from other stores.
> 
> In general, I would recommend to create a single store unless multiple stores are totally isolated.
> 
> In a single store scenario, if we need to extract common logic, we might extract store creator functions partially.
> 
> ```js
> const createFetcher = (prefix, fetchFunc) => (set, get) => ({
>   [prefix + 'result']: null,
>   [prefix + 'loading']: false,
>   [prefix + 'error']: null,
>   [prefix + 'fetch']: async (arg)=> {
>     try {
>       set({ [prefix + 'loading']: true })
>       const result = await fetchFunc(arg, { set, get })
>       set({ [prefix + 'loading']: false, [prefix + 'result']: result })
>     } catch(error) {
>       set({ [prefix + 'loading']: false, [prefix + 'error']: error })
>     }
>   },
> });
> 
> const fooFetcher = ('foo', async (id, { set, get }) => { ... });
> const barFetcher = ('bar', async (id, { set, get }) => { ... });
> 
> const useStore = create((set, get) => ({
>   ...fooFetcher(set, get),
>   ...barFetcher(set, get),
> }))
> ```
> 
> (Note: I never actually tried this approach...)

Nice! That should get the trick done I guess.
Lastly, sorry to bother you with this, but I do lose the typing/autocomplete with this example on `useStore`.

I currently have this:

```js
import create, { GetState, SetState, State } from "zustand";

// Not sure how to type fetchFunc ---------------------------V-------V
const createFetcher = (prefix: string, fetchFunc: (...args: any) => any) => (
  set: SetState<State>,
  get: GetState<State>
) => ({
  [`${prefix}result`]: null,
  [`${prefix}loading`]: false,
  [`${prefix}error`]: null,
  [`${prefix}fetch`]: async (arg: any) => { // <----------- not sure how to type this
    try {
      set({ [`${prefix}loading`]: true });
      const result = await fetchFunc(arg, { set, get });
      set({ [`${prefix}loading`]: false, [`${prefix}result`]: result });
    } catch (error) {
      set({ [`${prefix}loading`]: false, [`${prefix}error`]: error });
    }
  }
});

const fooFetcher = createFetcher("foo", async (id, { set, get }) => {
  console.log("Calling fooFetcher...");
  return { foo: "fetcher" }; // returned value should set the correct typing of this function's return type
});

export const useStore = create((set, get) => ({
  ...fooFetcher(set, get)
}));

// React Component
const MyComponent = () => {
  const store = useStore();
  store.xxxx // <------- no typing/autocomplete
}
```

I'm only familiar with basic usage, not with these tricky typings.
Maybe it could also be a nice example for the docs as well :)

**Comment by dai-shi** [comment]
Oh, yeah, typing would be hard. Let me try.

```ts
const createFetcher = <Prefix extends string, Arg, Result>(
  prefix: Prefix,
  fetchFunc: (
    arg: Arg,
    opts: { set: SetState<State>; get: GetState<State> }
  ) => Promise<Result>
) => (set: SetState<State>, get: GetState<State>) => {
  type PrefixResult = `${Prefix}result`;
  type PrefixLoading = `${Prefix}loading`;
  type PrefixError = `${Prefix}error`;
  type PrefixFetch = `${Prefix}fetch`;
  return {
    [`${prefix}result`]: null,
    [`${prefix}loading`]: false,
    [`${prefix}error`]: null,
    [`${prefix}fetch`]: async (arg: Arg) => {
      try {
        set({ [`${prefix}loading`]: true });
        const result = await fetchFunc(arg, { set, get });
        set({ [`${prefix}loading`]: false, [`${prefix}result`]: result });
      } catch (error) {
        set({ [`${prefix}loading`]: false, [`${prefix}error`]: error });
      }
    }
  } as Record<PrefixResult, Result | null> &
    Record<PrefixLoading, boolean> &
    Record<PrefixError, Error | null> &
    Record<PrefixFetch, (arg: Arg) => Promise<void>>;
};

const fooFetcher = createFetcher("foo", async (id: number, { set, get }) => {
  console.log("Calling fooFetcher...");
  return { foo: "fetcher" };
});
```

[typescript playground](https://www.typescriptlang.org/play?ssl=44&ssc=1&pln=9&pc=1#code/C4TwDgpgBAysCGxoF4oCUIGMD2AnAJgDwDOwuAlgHYDmUAPlJQK4C2ARhLvVMSO9gBsANFCaUA1pWwB3SgD4A3AChQkKAAV4uYOXgC4iCIQAqUCAA8klfMVgIkIgNJnLEa7fEQQ2AGZRTqJ7efsZyUMhKUNwAFOrkmOImTmEMxgCUkTHRpIYAXP5p4WFxCUlQjikFyqrQMBDABkgmLlY2doZhqADemYTOFq0eXr7+ctFgWjp6+Zrauvr2RsbJIrgQYALwmBAA-Pls2IIQ8JRp+QBu2OT4ygC+yhZgeMBQNVAA4vWNSy1ubd+dKDRQrIMLGZRKHCUUhQTBrQwAMXqmAAFpxwlBCOo1j5yOZfu4eGQqNQRABBXCk9AQYhMATAMaZMA4vEzFnmISZHzIlEIsSYfLRTJRLTUfIU0nCqDYMDAYj5Lo8er5OoNRaEAEKKDUZUfL7qgFQW6ZEHFXDYFjkYhGDC0+lyJSmoHW4Aq-WGDWLOQiHWuvVqj0Ap09KJvbEQXHmW10l6oAAGABIuuHI7c1nbgHHlKHwNAU3iADLYeD4EkYxPJ9m3ATF0s0LOZMPsgCiuHNXHjSfz5lunHbDZzam7SOAqPLXar3NHKIHUDWwCYuEoUBDUSgAG0K8yI3i0zSY3GALr5ZgCYRSzdJ7epmslklH-I+PTWzlrjdbqt9vAPxh089vy8umvXcp1RH94F4ShMCBUVxUpYMpVDXAQBXRC1xdaJFUA4Ce1vOtqB-MgmGgW40mzN81yhGF0xjDF4GkeByBeUDeX5aJRRERUXR9eojTItCogwrCPx3XDa3vY8oCfAQX3fK8qxo+kf0Ul5SPIt9blhRAx2iL9cEKVcKKVYBMLkoCqzwiTH2fCARGwz822-SS9L49S12NDTMk0iDqRwAgsXZaN6REIKXgYU8BDCAAyKUMD8ohuyLO8aBEA4jhOaLYqwPAEpbRzcBEVt224CLMrfOKcoC0SR1RER2MpODqCdbELStIxLmuORFCUe4lEhbBoWYw4arRDtYXhJARs4aIACIfEOGaRAgkAoKBa4T1YDgCpXYyeNUhCoioo4ADoa2oWaAGE9AEMt5uwKbcGOp6Zv4qJ50XZdFTu-I5p5TgZqNO5+KAA)

I may prefer flat `set` and `get` in fetchFunc, instead of `opts` object.

**Comment by DalderupMaurice** [comment]
> Oh, yeah, typing would be hard. Let me try.
> 
> ```ts
> const createFetcher = <Prefix extends string, Arg, Result>(
>   prefix: Prefix,
>   fetchFunc: (
>     arg: Arg,
>     opts: { set: SetState<State>; get: GetState<State> }
>   ) => Promise<Result>
> ) => (set: SetState<State>, get: GetState<State>) => {
>   type PrefixResult = `${Prefix}result`;
>   type PrefixLoading = `${Prefix}loading`;
>   type PrefixError = `${Prefix}error`;
>   type PrefixFetch = `${Prefix}fetch`;
>   return {
>     [`${prefix}result`]: null,
>     [`${prefix}loading`]: false,
>     [`${prefix}error`]: null,
>     [`${prefix}fetch`]: async (arg: Arg) => {
>       try {
>         set({ [`${prefix}loading`]: true });
>         const result = await fetchFunc(arg, { set, get });
>         set({ [`${prefix}loading`]: false, [`${prefix}result`]: result });
>       } catch (error) {
>         set({ [`${prefix}loading`]: false, [`${prefix}error`]: error });
>       }
>     }
>   } as Record<PrefixResult, Result | null> &
>     Record<PrefixLoading, boolean> &
>     Record<PrefixError, Error | null> &
>     Record<PrefixFetch, (arg: Arg) => Promise<void>>;
> };
> 
> const fooFetcher = createFetcher("foo", async (id: number, { set, get }) => {
>   console.log("Calling fooFetcher...");
>   return { foo: "fetcher" };
> });
> ```
> 
> [typescript playground](https://www.typescriptlang.org/play?ssl=44&ssc=1&pln=9&pc=1#code/C4TwDgpgBAysCGxoF4oCUIGMD2AnAJgDwDOwuAlgHYDmUAPlJQK4C2ARhLvVMSO9gBsANFCaUA1pWwB3SgD4A3AChQkKAAV4uYOXgC4iCIQAqUCAA8klfMVgIkIgNJnLEa7fEQQ2AGZRTqJ7efsZyUMhKUNwAFOrkmOImTmEMxgCUkTHRpIYAXP5p4WFxCUlQjikFyqrQMBDABkgmLlY2doZhqADemYTOFq0eXr7+ctFgWjp6+Zrauvr2RsbJIrgQYALwmBAA-Pls2IIQ8JRp+QBu2OT4ygC+yhZgeMBQNVAA4vWNSy1ubd+dKDRQrIMLGZRKHCUUhQTBrQwAMXqmAAFpxwlBCOo1j5yOZfu4eGQqNQRABBXCk9AQYhMATAMaZMA4vEzFnmISZHzIlEIsSYfLRTJRLTUfIU0nCqDYMDAYj5Lo8er5OoNRaEAEKKDUZUfL7qgFQW6ZEHFXDYFjkYhGDC0+lyJSmoHW4Aq-WGDWLOQiHWuvVqj0Ap09KJvbEQXHmW10l6oAAGABIuuHI7c1nbgHHlKHwNAU3iADLYeD4EkYxPJ9m3ATF0s0LOZMPsgCiuHNXHjSfz5lunHbDZzam7SOAqPLXar3NHKIHUDWwCYuEoUBDUSgAG0K8yI3i0zSY3GALr5ZgCYRSzdJ7epmslklH-I+PTWzlrjdbqt9vAPxh089vy8umvXcp1RH94F4ShMCBUVxUpYMpVDXAQBXRC1xdaJFUA4Ce1vOtqB-MgmGgW40mzN81yhGF0xjDF4GkeByBeUDeX5aJRRERUXR9eojTItCogwrCPx3XDa3vY8oCfAQX3fK8qxo+kf0Ul5SPIt9blhRAx2iL9cEKVcKKVYBMLkoCqzwiTH2fCARGwz822-SS9L49S12NDTMk0iDqRwAgsXZaN6REIKXgYU8BDCAAyKUMD8ohuyLO8aBEA4jhOaLYqwPAEpbRzcBEVt224CLMrfOKcoC0SR1RER2MpODqCdbELStIxLmuORFCUe4lEhbBoWYw4arRDtYXhJARs4aIACIfEOGaRAgkAoKBa4T1YDgCpXYyeNUhCoioo4ADoa2oWaAGE9AEMt5uwKbcGOp6Zv4qJ50XZdFTu-I5p5TgZqNO5+KAA)
> 
> I may prefer flat `set` and `get` in fetchFunc, instead of `opts` object.

That works! If I use the `fooFetcher` directly 😄 
The only downside is that inside the `createFetcher` you lose the typings (get and set use State and State is just a record of unknowns)
and when you use the `useStore` (which also uses the State) you also don't have any typing typings/autocompletion.

I'll see if I can figure out how it's done, thanks for all the help already!

```js
const fooFetcher = createFetcher("foo", async (id: number, set, get) => {
  console.log("Calling fooFetcher...");
  set({ foo: "fetcher" }); // no type checking/autocomplete
  get().x; // no typing/autocomplete
  return { foo: "fetcher" };
});

// useStore loses all typings
export const useStore = create((set, get) => ({
  ...fooFetcher(set, get)
}));
```

**Comment by DalderupMaurice** [comment]
> Oh, yeah, typing would be hard. Let me try.
> 
> [typescript playground](https://www.typescriptlang.org/play?ssl=44&ssc=1&pln=9&pc=1#code/C4TwDgpgBAysCGxoF4oCUIGMD2AnAJgDwDOwuAlgHYDmUAPlJQK4C2ARhLvVMSO9gBsANFCaUA1pWwB3SgD4A3AChQkKAAV4uYOXgC4iCIQAqUCAA8klfMVgIkIgNJnLEa7fEQQ2AGZRTqJ7efsZyUMhKUNwAFOrkmOImTmEMxgCUkTHRpIYAXP5p4WFxCUlQjikFyqrQMBDABkgmLlY2doZhqADemYTOFq0eXr7+ctFgWjp6+Zrauvr2RsbJIrgQYALwmBAA-Pls2IIQ8JRp+QBu2OT4ygC+yhZgeMBQNVAA4vWNSy1ubd+dKDRQrIMLGZRKHCUUhQTBrQwAMXqmAAFpxwlBCOo1j5yOZfu4eGQqNQRABBXCk9AQYhMATAMaZMA4vEzFnmISZHzIlEIsSYfLRTJRLTUfIU0nCqDYMDAYj5Lo8er5OoNRaEAEKKDUZUfL7qgFQW6ZEHFXDYFjkYhGDC0+lyJSmoHW4Aq-WGDWLOQiHWuvVqj0Ap09KJvbEQXHmW10l6oAAGABIuuHI7c1nbgHHlKHwNAU3iADLYeD4EkYxPJ9m3ATF0s0LOZMPsgCiuHNXHjSfz5lunHbDZzam7SOAqPLXar3NHKIHUDWwCYuEoUBDUSgAG0K8yI3i0zSY3GALr5ZgCYRSzdJ7epmslklH-I+PTWzlrjdbqt9vAPxh089vy8umvXcp1RH94F4ShMCBUVxUpYMpVDXAQBXRC1xdaJFUA4Ce1vOtqB-MgmGgW40mzN81yhGF0xjDF4GkeByBeUDeX5aJRRERUXR9eojTItCogwrCPx3XDa3vY8oCfAQX3fK8qxo+kf0Ul5SPIt9blhRAx2iL9cEKVcKKVYBMLkoCqzwiTH2fCARGwz822-SS9L49S12NDTMk0iDqRwAgsXZaN6REIKXgYU8BDCAAyKUMD8ohuyLO8aBEA4jhOaLYqwPAEpbRzcBEVt224CLMrfOKcoC0SR1RER2MpODqCdbELStIxLmuORFCUe4lEhbBoWYw4arRDtYXhJARs4aIACIfEOGaRAgkAoKBa4T1YDgCpXYyeNUhCoioo4ADoa2oWaAGE9AEMt5uwKbcGOp6Zv4qJ50XZdFTu-I5p5TgZqNO5+KAA)
> 
> I may prefer flat `set` and `get` in fetchFunc, instead of `opts` object.

Did some adjustments, got this far: [Typescript Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AYwDYEMrDjAnmbAZRnRmwF44AlFaBAHgGcYoBLAOwHM4AfOdgK4BbAEbAovOI1yiIqADRwB7ANbsIAd3YA+ANwAoUJFiIUGLDnzYACphit0qYqWD0AKnFBl2CRnGdkigDSniDevnAqwLgQAGZwHpRRMfFu2nCUABTWrMgq7sHpfG4AlJKZmcwuAFwJZeTpOXkFcEFFdQZG0PBIaJjYeAT+JGSEwKgoMNDuoeF+AcCKAKrpWVVktaUZ6Uud4N2mfRaD2ACiAI4Cjqx4AMIAFihRUO6rcJUjwJuK7MAaC5t6ukRBA5MB0Ow9sYemZ+pYhgsADKsZjAX4vNIZd7rL4JRRgLAAN1YEAEjABdW2cEJEFYCChB165gGVmGLkIqFywGRqPRryxlU5yFxbnxRJJZI5XMBVJpdIZJg4ZCgsXQwv8AhEjGQbDEMy8aIiC3SAG99HALe9ObzxLUkSjvOJXiVapkgdTafTzZb6AspcLtJlrY6oHbPv7uQ60U6-ULgNpFIxxpNoGH2cnkFMMYpY1yE55Ltc8AAxdgAflqFyunLujzyMfDce0Lve7rlXoAvoZ9iYmXCTv5gDAFvqwob5p83mbLXB6CEDT4-Mk4glA2A7A5ULVbLBNyPRa181gwBhhRW4CCwRCW+2DB2FTCjiyhgBxIf72bjtlkN5uqluB9DmZeFsAAEWAZgoAgXABTbT1AKVcRVXVYhoGAABBMBWFHOZv3jOBp0tJNh0+O130+V4DBnThyJqOA3xIlxKO9C1GE1bVdVxQh2J1Vg9TSKjLSQSDoNqcCRNwO9u2hID+1ZBZbiwUhpg8BcjU+RRbjJKYhDGRiyCxPT920X9iNqLTmAgXTaMCOAaJgWoGOMxR0CwsM0Mw7C0ndADpIORCVTVbAliTVCsBwr9jQIljW02QSLXoFZKgzLM01GFKVOWfNgELGtcFLc8qyLXAHieJ0VhbXYYuIikjIogSYvsiknPqvRqp4zi7Q6vjXAamdhJYUS4HEwbJP0Ls-N7YBVQEVB4FiZRMxJdg4B1cEyHcBZP0XPDAzW9lSLwxT1pUqK+DCjCsM2ydKtCrNeuNAx9GQCB2GYValLIYsh2QR4JEoehrCwWJWBAbaIkgjhOEUdCoGh6gINmmBA29AlptB7dgdB+RvViH77mLRbanoQnUCcT5wYnFwUZnTBOFqWHoeqocyP01xSfJ6mceoln6Js9nZs5n9vXdIGrJRVwaDYub0gAellhJHiTOyhzgCEECkVWxFQTQ4D+7A4SEB0rAQH5gGACIpgvbAOYWfR3WShzBzZ31J0UezHP513qfdQiByB9GQClpGsQAAwAEhNAOQZADtg7m0PBP9rGQERCB0AQKGw8j6PQY7NOM6hxPvWTwPTigKD-rgCOo5Tjty8r4uLVLmPvpgX7s9rwOOzb36m7gLAYAEKAVsIi0AG0a7RmO48RhOAF1akEMnuctSfI+nvOC8zrhQ8XuBVVQJNV4nqe64b6A96XwWT7gdeTU32Pe-uK+1ekdhkHeOmGbh32YubqAMEx4zk1jATIJo75n27tvIu+8WACGwB2Eo8UQEvTevALA0t4CUHQBodANwD740Jh-TIdNExDndkOZB-8iJDnAZAjedcYG733ofY+DCH513jjAV+mCQ5IJQRaDsq1SAd0yOISuZRgEzmIvQ++j987px3pwV+bDFgcIURfKAr8JHQDgAImhXYZxGP0W-BGL0oAMFzkHOeMBFDcMkMvVA6QABkMUaAWKsSnZh8NLwTAhK49xtBLGAxTloxQWjHGC0CTODxdBQmB2fooUhcMf6cFFlBI2SZ6DthMneJ6aD3qxFBM-cQWJ9pfXxuITIAAiYpEAakuXfp-TIdJr6iHEOQuxKsYB-wtIUsEAA6HWnBam3EcJyLgB8SlVKgIM+ZNTqGsToRA+ptQ6mzJqfo5BcB5azgALSHLgAAeXYKgGC9TSkSGSKEB0jAyzensm6QZIBdC7IVvQQ5+y4AADkIDwiht6Qew9R7TIgOsvG7c-pbPvONahz1XrvUvFc8pn1gBXNqZeRpb9cAf3eG0-gwgxBQC6ZQ3pVJCIDImMMiAoyanjLJlnZFsz5mDMWYJWREDLzrLEFC8QMKdl7M+Uc055yLwzL5dc6ItzmD3MeXQkoLy3lCq+b8-5gxAUWmBSPAi4rwVwBqby36-L9F3nhQOW2FNKBbTcRaGgQ8R5uCsPQE4K5LmzJiQjB17AnUEBdVYFczLJVtUmvAQp8AyTAAuqi9aAsybGgqMRMlDtCKsvdZKx2ybV6sqDcaqAmaeklDhfC-QQA)
I created a State object for the combined state and passed it through, although it's not fully working.

**Comment by leyiang** [comment]
> Oh, yeah, typing would be hard. Let me try.
> 
> ```ts
> const createFetcher = <Prefix extends string, Arg, Result>(
>   prefix: Prefix,
>   fetchFunc: (
>     arg: Arg,
>     opts: { set: SetState<State>; get: GetState<State> }
>   ) => Promise<Result>
> ) => (set: SetState<State>, get: GetState<State>) => {
>   type PrefixResult = `${Prefix}result`;
>   type PrefixLoading = `${Prefix}loading`;
>   type PrefixError = `${Prefix}error`;
>   type PrefixFetch = `${Prefix}fetch`;
>   return {
>     [`${prefix}result`]: null,
>     [`${prefix}loading`]: false,
>     [`${prefix}error`]: null,
>     [`${prefix}fetch`]: async (arg: Arg) => {
>       try {
>         set({ [`${prefix}loading`]: true });
>         const result = await fetchFunc(arg, { set, get });
>         set({ [`${prefix}loading`]: false, [`${prefix}result`]: result });
>       } catch (error) {
>         set({ [`${prefix}loading`]: false, [`${prefix}error`]: error });
>       }
>     }
>   } as Record<PrefixResult, Result | null> &
>     Record<PrefixLoading, boolean> &
>     Record<PrefixError, Error | null> &
>     Record<PrefixFetch, (arg: Arg) => Promise<void>>;
> };
> 
> const fooFetcher = createFetcher("foo", async (id: number, { set, get }) => {
>   console.log("Calling fooFetcher...");
>   return { foo: "fetcher" };
> });
> ```
> 
> [typescript playground](https://www.typescriptlang.org/play?ssl=44&ssc=1&pln=9&pc=1#code/C4TwDgpgBAysCGxoF4oCUIGMD2AnAJgDwDOwuAlgHYDmUAPlJQK4C2ARhLvVMSO9gBsANFCaUA1pWwB3SgD4A3AChQkKAAV4uYOXgC4iCIQAqUCAA8klfMVgIkIgNJnLEa7fEQQ2AGZRTqJ7efsZyUMhKUNwAFOrkmOImTmEMxgCUkTHRpIYAXP5p4WFxCUlQjikFyqrQMBDABkgmLlY2doZhqADemYTOFq0eXr7+ctFgWjp6+Zrauvr2RsbJIrgQYALwmBAA-Pls2IIQ8JRp+QBu2OT4ygC+yhZgeMBQNVAA4vWNSy1ubd+dKDRQrIMLGZRKHCUUhQTBrQwAMXqmAAFpxwlBCOo1j5yOZfu4eGQqNQRABBXCk9AQYhMATAMaZMA4vEzFnmISZHzIlEIsSYfLRTJRLTUfIU0nCqDYMDAYj5Lo8er5OoNRaEAEKKDUZUfL7qgFQW6ZEHFXDYFjkYhGDC0+lyJSmoHW4Aq-WGDWLOQiHWuvVqj0Ap09KJvbEQXHmW10l6oAAGABIuuHI7c1nbgHHlKHwNAU3iADLYeD4EkYxPJ9m3ATF0s0LOZMPsgCiuHNXHjSfz5lunHbDZzam7SOAqPLXar3NHKIHUDWwCYuEoUBDUSgAG0K8yI3i0zSY3GALr5ZgCYRSzdJ7epmslklH-I+PTWzlrjdbqt9vAPxh089vy8umvXcp1RH94F4ShMCBUVxUpYMpVDXAQBXRC1xdaJFUA4Ce1vOtqB-MgmGgW40mzN81yhGF0xjDF4GkeByBeUDeX5aJRRERUXR9eojTItCogwrCPx3XDa3vY8oCfAQX3fK8qxo+kf0Ul5SPIt9blhRAx2iL9cEKVcKKVYBMLkoCqzwiTH2fCARGwz822-SS9L49S12NDTMk0iDqRwAgsXZaN6REIKXgYU8BDCAAyKUMD8ohuyLO8aBEA4jhOaLYqwPAEpbRzcBEVt224CLMrfOKcoC0SR1RER2MpODqCdbELStIxLmuORFCUe4lEhbBoWYw4arRDtYXhJARs4aIACIfEOGaRAgkAoKBa4T1YDgCpXYyeNUhCoioo4ADoa2oWaAGE9AEMt5uwKbcGOp6Zv4qJ50XZdFTu-I5p5TgZqNO5+KAA)
> 
> I may prefer flat `set` and `get` in fetchFunc, instead of `opts` object.

I have two stores in my project that share same logics. I want to reuse them and add little unique logic to each of them. Thanks to Dai-Shi's reply, I can do it like this:

```ts
interface ItemWithID {
    id: number;
}

export interface ListStoreState<T> {
    items: T[],
    appendItems: (items: T[]) => void;
    // other common logic
} 

export const createListStoreLogic = <T extends ItemWithID>() => (
    set: StoreApi<ListStoreState<T>>['setState'],
    get: StoreApi<ListStoreState<T>>["getState"]
) => ({
    appendItems: (items: T[]) => {
        set(state => {
            const newList = [ ...state.items, ...items ];
            return { items: newList }
        });
    },
})

// Actual store:
interface FolderStoreState extends ListStoreState<Folder> {
     // unique states and logics
}

export const useFolderStore = create<FolderStoreState>((set, get) => ({
    items: [],
    ...createListStoreLogic<Folder>()(set, get),
}));

```
Hope this could be useful.
