### ISSUE TITLE
How to use zustand in a non-singleton way

### ISSUE THREAD

**Issue by csr632** [react-spring/zustand#162]
In current documentation, store instance is created when the module is executed. **All component instances will bind to the same store instance(singleton pattern).** Zustand is similar to redux in this way.

But sometimes this is not what I want. Sometimes I want **each `ComponentA` instance has its own `StoreA` instance**. In other words, `ComponentA instance lifetime === StoreA instance lifetime`. `ComponentA` can share its `StoreA` instance to its children.
This pattern is very suitable when the data lifetime should be same with component instance lifetime.

Is there a standard way to do this?

**Comment by dai-shi** [comment]
We had a discussion: #128
In short, it's technically possible, at least for now.
However, because it's a bit tricky (can lead to violate rules of hooks, if not done properly), we don't document it for now as it's only for power users.

**Comment by a-eid** [comment]
@dai-shi thanks, 
however I personally don't think the solutions presented in #128 is appealing.
I would like to know more about the second project

**Comment by merisbahti** [comment]
i'm interested in this too, similar to useReducer but with the nice api of zustand

**Comment by dai-shi** [comment]
https://github.com/react-spring/jotai is out. Please check it. It's designed for non-singleton.

If you have question about Jotai, please file an issue there.

**Comment by dai-shi** [comment]
I was about to close this issue, but @merisbahti 's question still seems valid.

> i'm interested in this too, similar to useReducer but with the nice api of zustand

Would you elaborate what you want? what would it be like?

**Comment by dai-shi** [comment]
Let me close this.
If someone has a further question, please file a new issue.
