### ISSUE TITLE
[useStore, api] = create() is deprecated and will be removed in v4

### ISSUE THREAD

**Issue by Jossnaz** [react-spring/zustand#166]
hi guys

>[useStore, api] = create() is deprecated and will be removed in v4

how else will I get access to API?

btw I had to go back to using API because I, weirdly, got a 

>An unhandled error was caught from submitForm() Error: Invalid hook call. Hooks can only be called inside of the body of a function component

in a formik onSubmit form call... very weird.

But anyhow, it seems to work via api. How else is access to api done?

**Comment by dai-shi** [comment]
Hi, sorry for the confusion.

```js
const [useStore, api] = create(...)
```
can be written
```js
const useStore = create(...)
const api = useStore
```
in v3. It looks tricky, but it works.

----

If you really hesitate to do the above, the alternative way is:
```js
import createStore from 'zustand/vanilla'
import createHook from 'zustand'

const api = createStore(...)
const useStore = createHook(api)
```

**Comment by Jossnaz** [comment]
so 

`useStore` and `api` is the same thing now, that's what you are saying?

so I can do

```js
const useStore = create(...);
useStore.getState()...
```

???

**Comment by dai-shi** [comment]
> `useStore` and `api` is the same thing now, that's what you are saying?

Yeah, it's like overloaded.

> ```js
> const useStore = create(...);
> useStore.getState()...
> ```

Right. Check readme: https://github.com/react-spring/zustand#readingwriting-state-and-reacting-to-changes-outside-of-components

> that would leave the weird hook problem from above though.

Do you mean `Error: Invalid hook call.`? I don't think it happens.

**Comment by Jossnaz** [comment]
>that would leave the weird hook problem from above though.
>
>Do you mean Error: Invalid hook call.? I don't think it happens.

yeah you were right. I somehow had brain fog from working too much even though, it isn't as clear anyhow.

I did basically, after  a lot of simplification, did this:

```jsx
const App = () => {

return    <Formik
            initialValues={{
            }}
            onSubmit={(values, formikHelpers) => {
            const {count, inc} = useStore();
                console.error("count", count);
            }
            }
        >

```

which doesnt work.

This was the fix:
```jsx
const App = () => {
            const {count, inc} = useStore();

return    <Formik
            initialValues={{
            }}
            onSubmit={(values, formikHelpers) => {

                console.error("count", count);
            }
            }
        >

```
