### ISSUE TITLE
Store is returning undefined

### ISSUE THREAD

**Issue by DavidShefcik** [react-spring/zustand#170]
So I am trying to use Zustand version 3.0.2 and I've been following the README but it does not seem to be working. Every time I attempt to use a store it returns undefined. I know the actual store works because when I console log it's contents in the file where it's created I can see the values. I am using TypeScript in a React Native application but I don't think that'd cause any issues.
```
const userPersist = persist<UserStore>(
  (set: SetState<UserStore>, get: GetState<UserStore>) =>
    set({
      user: initialUser,
      setUser: (newUser: User) =>
        set({
          user: newUser,
        }),
      updateUser: (fieldsToUpdate: User) =>
        set({
          user: {...get().user, ...fieldsToUpdate},
        }),
      resetUser: () =>
        set({
          user: initialUser,
        }),
    }),
  "user",
);

const useStore = create(userPersist);
```
initialUser is an object with values so that should not be returning undefined. I keep trying to access the store like this in a React component but it returns undefined for everything.
```
const {user, resetUser} = useUserStore(
    (state: UserStore) => ({
      user: state.user,
      resetUser: state.resetUser,
    }),
    shallow,
 );
console.log(user); // undefined
console.log(resetUser); undefined
```
Even trying it with just getting one value returns undefined.
```
  const user = useUserStore((state) => state.user);
  console.log(user); // undefined
```

**Comment by dai-shi** [comment]
Hi, thanks for reporting! Can we see how `persist` is implemented? It would be very nice if you can provide a codesandbox repro too.

**Comment by DavidShefcik** [comment]
Turns out the issue was caused by my own persist middleware, oops! It kept trying to pull the values from AsyncStorage but due to me trying to handle it synchronously it would return undefined. I'll close the issue.
