### ISSUE TITLE
devtools don't always log

### ISSUE THREAD

**Issue by TkDodo** [react-spring/zustand#171]
devtools log fine as long as you call `set` (inside the `create` function). However, if you use the `useStore.setState` function to set some state, devtools doesn't log it.

Here is a minimal reproduceable example:

https://codesandbox.io/s/beautiful-ellis-17s7g

The `increase` function logs fine, the `setToFive` function does not.

Judging from the code, I think it is because `namedSet` is kept locally here:

https://github.com/react-spring/zustand/blob/a6417ce460a31cec94adc4a32c55d1abc98a00ba/src/middleware.ts#L54-L63

Currently, the middleware can only return the initialState, but since we want to wrap the setState function, we would somehow need to return / expose that function as well. What do you think?

**Comment by dai-shi** [comment]
Right, api.setState is not patched by devtools. It might be a bit tricky to do so, because it is called by `set`. We could add `api.namedSet`, but using that in production is weird...
