### ISSUE TITLE
typing problem storeApi outside of react with immer middleware

### ISSUE THREAD

**Issue by kurosh-z** [react-spring/zustand#173]
@kurosh-z Hey, I fixed it recently. Please check the example in #169. If it doesn't work, would you please file a new issue?

_Originally posted by @dai-shi in https://github.com/react-spring/zustand/issues/75#issuecomment-684075606_

Hi , 
 #169  actually solved the typing problem inside of react. But if you use the setState api outside of react, typescript requires you to return the state.

```typescript
// outside of react
useStore.setState((state) => {
  state.bb.b1 = true;
});
```
<img width="761" alt="Screen Shot 2020-09-01 at 3 21 31 PM" src="https://user-images.githubusercontent.com/32224317/91856407-d609b080-ec66-11ea-8ea0-2023568b37d0.png">

codeSandbox :

https://codesandbox.io/s/pedantic-flower-immerzustand-forked-ptso7?file=/src/App.tsx

**Comment by dai-shi** [comment]
Thanks for opening a new issue.

The type is actually correct, because the immer middleware doesn't modify `api.setState`.
The reason why your codesandbox seem to work is setState is called to **mutate** the state before React component renders.

Here's the example that breaks: https://codesandbox.io/s/pedantic-flower-immerzustand-forked-i47xs

So, how to solve this. Making another immer middleware that also patches `api.setState` is not trivial because of typing as you implied.
I would probably make a patched setState after creating the store.
```js
const useStore = create(...)
const setStateWithImmer = fn => useStore.setState(produce(fn))
```

**Comment by itstheandre** [comment]
Hey @dai-shi !
With version 3.1.* your example stopped working in terms of typings.

```Type 'T' does not satisfy the constraint 'Record<string | number | symbol, unknown>'```

what would be the new way of typing this?

**Comment by dai-shi** [comment]
@itstheandre Hey! Which example is it?

https://github.com/react-spring/zustand/issues/183#issuecomment-688848124
Check this. I hope your issue is the same.

**Comment by itstheandre** [comment]
Hey @dai-shi 
The example you copied in the answers above.
I basically just updated the version from 3.0.2 to 3.1.1 and i start having the error above.

I dont think the issue in that comment is the same, because here you are "inline" typing the case

**Comment by dai-shi** [comment]
Ah, the codesandbox example in my comment. Here's the fixed version: https://codesandbox.io/s/pedantic-flower-immerzustand-forked-5zdy9

The immer middleware with types:
```ts
const immer = <T extends State>(
  config: StateCreator<T, (fn: (state: T) => void) => void>
): StateCreator<T> => (set, get, api) =>
  config((fn) => set(produce(fn) as (state: T) => T), get, api);
```

> Very weird the you need to extend it

It's a long story (also discussed in various TS issues), but that's how it works.

**Comment by dai-shi** [comment]
Let me close this issue as the first question is answered and now the context is a bit changed.

I added the above immer snippet in readme.md.
