### ISSUE TITLE
I think we need the dependencies array back...

### ISSUE THREAD

**Issue by timkindberg** [react-spring/zustand#18]
I think we need dependencies back. When I upgraded to 0.1.1 my code broke. I like to create selectors in my state and those selectors use external variable dependencies. It's probably easiest to just look at a working example of the issue.

https://codesandbox.io/s/8x2ylkzpj8

I posted this in a comment, but then realized I should probably open an issue.

**Comment by drcmda** [comment]
@JeremyRH

**Comment by drcmda** [comment]
Playing around some more, the store is never updated since nothing in it changes, so it doesn't fire subscribers. setId(id => id + 1) just returns arg0, but doesn't call set. Hence the selector is called only once, initially. Isn't this expected, though?

**Comment by drcmda** [comment]
On second thought, you're right, when the selector changes it can yield another result, so it should definitively be possible to run a diff even though the store hasn't been changed.

**Comment by timkindberg** [comment]
Exactly. We should either add back `dependencies` or be more restrictive how the selecting can happen. Because if I can write code like this to select state I’m expecting it to work.

**Comment by drcmda** [comment]
Like this maybe? https://codesandbox.io/s/o7nky5wwj5

This would also work if you remove the [id], in that case it would call the selector on every render, more or less like redux works. If you supply the selector, it runs only on memoize changes. I haven't tested if this causes extra render calls now.

**Comment by timkindberg** [comment]
Yeah, you bring up extra renders... I worry that the component will render, triggering the `React.useEffect(() => void ping(), deps)` which in turn will trigger another render.

**Comment by timkindberg** [comment]
I think this seems like a pretty good solution, barring it doesn't cause a bunch of extra renders...

**Comment by JeremyRH** [comment]
I think we can solve this issue without adding the dependencies back. We can run the selector on every call to `useStore` and return that slice instead of returning the state from React's `useState`. I'm not sure if this will cause unwanted side effects though. I'll test this out today.
