### ISSUE TITLE
MyStore does not satisfy the constraint 'Record<string | number | symbol, unknown>'.

### ISSUE THREAD

**Issue by dutzi** [react-spring/zustand#183]
The following code runs fine on `3.0.0`:

```ts
import create from 'zustand';

type PlayState = 'playing' | 'paused' | 'stopped';

export interface PlayerStore {
  playState: PlayState;
  showOutline: boolean;
  setPlayState: (state: PlayState) => void;
}

export const usePlayerStore = create<PlayerStore>((set) => ({
  playState: 'paused',
  showOutline: false,
  setPlayState: (playState) => set(() => ({ playState })),
}));
```

But breaks on `3.1.0`, with the following error message, by tsc:

```
PlayerStore does not satisfy the constraint 'Record<string | number | symbol, unknown>'.
```

**Comment by dutzi** [comment]
It seems like the type definition for what a store is, does not cover all the possible use cases (boolean, function, ...)

**Comment by dai-shi** [comment]
Thanks for reporting.
https://codesandbox.io/s/great-liskov-yzerc
It's interesting. If we use `type` instead of `interface`, it works. 🤔

**Comment by dai-shi** [comment]
OK, here's the fix using interface.
https://codesandbox.io/s/wonderful-bohr-7oqxn
```ts
export interface PlayerStore extends State {
  playState: PlayState;
  showOutline: boolean;
  setPlayState: (state: PlayState) => void;
}
```

Is it acceptable for your use case?

**Comment by dutzi** [comment]
Sure, it's not a lot to change :)

**Comment by dai-shi** [comment]
Added a link: https://github.com/react-spring/zustand/releases/tag/v3.1.0
