### ISSUE TITLE
devtools: commit button doesn't work

### ISSUE THREAD

**Issue by TkDodo** [react-spring/zustand#184]
Not sure if this is `zustand` specific - but clearing the log by pressing `Commit` works in a standard redux-app, but when the store is `zustand`, the button just doesn't do anything. You can try that out here:
https://codesandbox.io/s/affectionate-davinci-kzdte

Click `increase` a bunch of times, look at the redux dev tools and press `Commit`

Not sure if this is a bug or maybe a missing feature that would need to be implemented separately .. ?

**Comment by dai-shi** [comment]
Confirmed the issue. I think it's a missing feature. It behaves the same with v1.0.7.

Would you like to tackle it?

**Comment by TkDodo** [comment]
> Would you like to tackle it?

Yes, I'll give it a try, I hope I find the time soon.
For reference:

- documentation: https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md
- I found [this implementation](https://github.com/aurelia/store/commit/86b7edab8efc025c7fa10491db66bd305f338922#diff-cfb8e44b6757fd740446e9e4486b73c1R337) of the aurelia store, so maybe all we need to do is handle the `COMMIT` message [somewhere here](https://github.com/react-spring/zustand/blob/2ee2928b85f9432b4e1646de5c5952735e032553/src/middleware.ts#L75-L85).
