### ISSUE TITLE
Improve Typescript support and only make the first generic type required.

### ISSUE THREAD

**Issue by Luxizzle** [react-spring/zustand#21]
As soon as you start messing with the first generic, you are quickly hit by the second and third required generics. This could probably be improved by giving those default types.

Also exporting some of the types and an interface for the store api would be a nice addition. This way we can create functions that require the store api as a parameter for example.

I've already tried implementing some of these, but sadly broke the auto-generation of the `State` generic, so no auto-completion for `set` and `get` and so on, which probably isn't so nice for none typescript users.

https://github.com/Luxizzle/zustand/commit/b095e8cd63ea56854ae8cd61dc28faa604049ac8

**Comment by JeremyRH** [comment]
> This could probably be improved by giving those default types.
I thought `extends` automatically gives them a default type (of the extended type). Can you explain further?
> Also exporting some of the types and an interface for the store api would be a nice addition.
Good idea. Some types/interfaces should be exported like `UseStore` and `StoreApi` but I don’t see a reason to export any other types. I want to limit the chance of making breaking changes in the future.

Thanks for the changes and suggestions. You can make a PR even if it breaks stuff. I won't merge it until it's fixed, but we can work on fixing it together.

**Comment by Luxizzle** [comment]
Alright, i made a pull request #22.
