### ISSUE TITLE
Feature request: api.subscribe(callback, /*selector*/)

### ISSUE THREAD

**Issue by drcmda** [react-spring/zustand#23]
We need a way to bind components to the store without causing updates (for rapid micro updates that would cause lots of render requests). See: https://twitter.com/0xca0a/status/1133329007800397824

In theory this can be done using subscribe, but it can't select state. My suggestion would be an optional second arg:

```jsx
const [, api] = create(set => ({
  a: 1,
  b: 2,
  set
}))
const unsub = api.subscribe(state => console.log(state), state => state.b)
api.getState().set(state => ({ ...state, b: 3 }))

// console would say: 3
```

Now components could receive transient updates and also disconnect on unmount via useEffect:

```jsx
function Person({ id }) {
  useEffect(() =>
    api.subscribe(state => /*do something*/, state => state.persons[id]),
    [id]
  )
```

@JeremyRH what's your opinion? And if you're fine with it, could you help getting this in? I'm still learning TS and i'm getting some typing issues, i had to set the internal listeners array to "StateListener-any" but it looked good so far:

```jsx
  const listeners: Set<StateListener<any>> = new Set()

  const setState = (partialState: PartialState<State>) => {
    state = Object.assign(
      {},
      state,
      typeof partialState === 'function' ? partialState(state) : partialState
    )
    listeners.forEach(listener => listener(state))
  }

  const getState = () => state

  function subscribe<U>(
    callback: StateListener<U>,
    selector?: StateSelector<State, U>
  ) {
    let listener = callback
    if (selector) {
      let stateSlice = selector(state)
      listener = () => {
        const selectedSlice = selector(state)
        if (!shallowEqual(stateSlice, (stateSlice = selectedSlice)))
          callback(stateSlice)
      }
    }
    listeners.add(listener)
    return () => void listeners.delete(listener)
  }
```

**Comment by JeremyRH** [comment]
This is great! It would be good to test the performance when React is not in development mode. I was seeing comparable speeds with the production version of React.

But this is definitely worth exploring. I was just prototyping something that involved updating the store without calling React's `dispatch` (not performance related). It seems like we should enable full features for reading and writing state outside of React. We might need to make some of the types less strict. I'll look into this today.

**Comment by JeremyRH** [comment]
It's difficult to define the function signature of StateListener. Apparently generics are inferred as `{}` if used before being assigned a type. StateSelector is the second argument so the generic `U` is not inferred yet when the StateListener type is defined. I was able to get it to work by reversing the parameter order: `subscribe(selector | listener, listener)` but I don't like it.

**Comment by drcmda** [comment]
you mean i could either do

    sub(state => console.log("state changed"))

or

    sub(state => state.x, x => console.log("x has changed"))

? 

I would actually prefer this : D but probably only because i don't know TS good enough to see the downsides (?)

**Comment by JeremyRH** [comment]
Yes, you would be able to do that. The selector function is optional and I'm used to optional parameters being last. Haha I guess it's mostly preference though. If you like it, I'm fine with it.

**Comment by drcmda** [comment]
Wound you merge it? I think this functionality would make it very versatile.
