### ISSUE TITLE
api.subscribe calls every subscriber even if state doesn't change

### ISSUE THREAD

**Issue by JeremyRH** [react-spring/zustand#24]
Adding an external subscriber using `api.subscribe` calls the subscriber on every `setState` call even if the state does not change. @drcmda Is this expected behavior? Fixing it could cause regressions if someone relies on it.

**Comment by drcmda** [comment]
This is normal, in Redux it’s the same, subs will fire for any state change. Same for useStore(). That’s why I thought a selector would be nice.

**Comment by JeremyRH** [comment]
I have a fix that's basically the same but does a shallow equal check I just wanted to open this issue to see if you had any more info on what the behavior should be and to reference this for a potential fix. I'll check if redux is the same.

**Comment by JeremyRH** [comment]
The selective `api.subscribe` change is how I discovered this. The behavior seemed inconsistent because a selective subscription would not be called unless its state changed but a non-selective one would be called every time even on no change.

**Comment by drcmda** [comment]
i think adding a shallow equal check isn't worth it tbh, it will just add overhead (for instance root objects with hundredes/thousands of objects in it, like a central-state hashmap). i think subscribe(fn) could expectedly fire on each setState. but i don't have a strong opinion on this one, if you like, add the additional check for consistency's sake.

Or, maybe, ... is it possible to run the check only over the partialState?

```jsx
const partial = typeof partialState === 'function' ? partialState(state) : partialState
if (shallowEqual(partial, state) { // <- will this work?
   state = Object.assign({}, state, partial)
```

**Comment by JeremyRH** [comment]
We can run the check only on the keys in partialState:
```ts
const setState: SetState<TState> = partialState => {
  if (
    partialState === state ||
    Object.entries(partialState).every(([key, value]) =>
      Object.is(state[key], value)
    )
  ) {
    return
  }
  state = Object.assign(
    {},
    state,
    typeof partialState === 'function' ? partialState(state) : partialState
  )
  listeners.forEach(listener => listener(state))
}
```

**Comment by drcmda** [comment]
I kept thinking about this, sadly this doesn't help when the user does `set(state => ({ ...state, something: 123 }))`

**Comment by drcmda** [comment]
Just saw this in the Redux docs:

subscribe(listener)

Adds a change listener. It will be called any time an action is dispatched, and some part of the state tree may potentially have changed. You may then call getState() to read the current state tree inside the callback.

I think they may have avoided the shallowdiff for the same reason.
