### ISSUE TITLE
Doesn't work on IE-10 and IE-11

### ISSUE THREAD

**Issue by collegeimprovements** [react-spring/zustand#28]
Would it be possible to support IE-10 and IE-11 by generating target files(via tsconfig) for IE-10,11 as well as modern browsers? 

Currently it gives syntax error in Internet Explorer.

**Comment by drcmda** [comment]
could you give me the errors? probably missing polyfills since we compile via babel-env without browser config.

**Comment by collegeimprovements** [comment]
It indeed worked. Thanks a lot :)

**Comment by HarrisonB** [comment]
Not sure if I should open up another issue, so I thought I'd ping here first: is there a reason that he ES Module source isn't transpiled for IE11 as well? If I am importing this with ES Module syntax with webpack for a web target, it's going to pick up the `module` entry point in `package.json` which includes stuff like `Object.assign` (a non-ES Module ES6) and not transpile it. I'd then have to transpile `zustand` myself. Is this intended?

Some reasoning/context: https://github.com/webpack/webpack/issues/1979#issuecomment-339738809
