### ISSUE TITLE
SetState & GetState Typescript declaration in create function arguments

### ISSUE THREAD

**Issue by jfbrazeau** [react-spring/zustand#32]
The `create` function typescript definition has a generic parameter that helps to define the final state that will be used : `TState extends State`. This state has to extend `State` (`Record<string, any>`) which is relevant for  a state.

Unfortunately both `set` and `get` parameters types don't use this generic parameter and instead are bound to `State` as we can see :
```  createState: (set: SetState<State>, get: GetState<State>, api: any) => TState```

It is not very anoying for the `set` parameter, but it is really a pity that when one uses the `get` method, the definition does not simply type the return to `TState` instead of the very neutral `State`.

Is it just a mistake ? Or is there a reason not to have used `TState` in `set: SetState<State>` and `get: GetState<State>` ? (I must admit that I would expect `set: SetState<TState>` and `get: GetState<TState>` instead).

I've created a (trivial) pull request : https://github.com/react-spring/zustand/pull/31

**Comment by JeremyRH** [comment]
TypeScript is unable to infer TState at the time the complier creates the `set` and `get` types. They default to `GetState<{}>` and `SetState<{}>`. You can specify your own types for these in the state creator function you pass in. I have tried to find a workaround for some time now and nothing seems to work.

**Comment by drcmda** [comment]
@JeremyRH would the overload that @dm385 suggested in the PR help?

**Comment by JeremyRH** [comment]
@drcmda I tried that. You lose type inference for JS. Also it's a little strange to create a wrapper function just to have your types inferred properly. I have another solution that we should test out. #35

**Comment by jfbrazeau** [comment]
I have tested the fix that is now that it is available in `1.0.2`. Unfortunately, as far as I can see, the proposed fix fixes very basic usages, but as soon as you plan to do generic things (in other words, as soon as you encapsulate the zustand `create` function in another function, the fix doesn't work anymore.
