### ISSUE TITLE
How can zustand distinguish between atomics and objects?

### ISSUE THREAD

**Issue by drcmda** [react-spring/zustand#36]
So this is something that @dm385 found by accidentally mutating a state object: https://codesandbox.io/s/strange-dew-4gv6k

```jsx
const [useStore] = create((set, get) => ({
  nested: { a: { a: 1  } }
  actions: {
    inc: () => {
      const nested = { ...get().nested }
      nested.a.a = nested.a.a + 1
      set({ nested })

function Test() {
  const nested = useState(state => state.nested)
```

Curiously the useStore hook doesn't fire when inc() is called. It mutates state, and if that weren't the case it would work, but the nested object *is* being exchanged here, so i was wondering why the hook didn't respond:

We distinguish between two selects, atomics and objects:

```jsx
// Object pick
const { number, string } = useStore(state => ({ number: state.number, string: state.string }))
// Atomic picks
const number = useStore(state => state.number)
const string = useStore(state => state.string)
```

I've never thought about this before, but it actually goes into the objects we return *every time* to make a shallow equal test, if they're self-made, like above, or if we select them right from state:

```jsx
// Doesn't do plain reference equality here, it will check each object prop for ref equality instead
const object = useStore(state => state.object)
```

The outcome is the same of course, if an object gets changed, even deeply, some prop is going to be different due to reducing. So at least we're safe, if users don't mutate it works, but can this lead to performance problems? For instance if a hash map object has 100.000 props it will have to go through them... : S

In Redux the hook does only a strict equality check by default, see: https://react-redux.js.org/api/hooks#equality-comparisons-and-updates Is this something we should do? And since we can't change the call signature since the 2nd arg is already given to dependencies, would this make sense?

```jsx
useStore(selector, deps)
useStore.shallow(selector, deps)
api.subscribe(selector, callback)
api.subscribe.shallow(selector, callback)
```

@JeremyRH

**Comment by drcmda** [comment]
I've made a reference implementation, untested, but my typescript experience is too weak right now to get even close to making it compile: https://gist.github.com/drcmda/50eb4a393085735bdb77016c636f663d

**Comment by JeremyRH** [comment]
I think we should find out when shallow equality checks cause performance issues. The check only happens on selected state, never the entire store.

I also think we should revisit the dependencies argument. I don't think it was worth adding to `useStore`. In my opinion, the performance concern is not common enough to add it as an option, especially when the user can do the same thing using `useCallback`, `useMemo`, or a static function instance.

We can add an optional user-defined equality check function to `useStore`. The same as react-redux's `useSelector` except we can default to `shallowEqual`. It can replace the dependencies argument if we remove it.

**Comment by drcmda** [comment]
At work we have tables that crab easily span thousands of objects (cad system), if you place a selector on it, it will have to browse through them.

Another thing I’ve noticed, people seem to just go for atomic picks, even if they know they can pick multiple items inborn go. That leads me to think that reduxes choice to make strict equal the default was perhaps justified. 

Good idea about the refs, useCallback is fine I Gieses and that would free up the 2nd arg.

What do you think?

’’’jsx
import { shallowEqual } from 'React-spring'

useStore(state => state.nestedObject)
useStore(state => ({ a: state.a, b: state.b }), shallowEqual)
’’’

**Comment by JeremyRH** [comment]
> But it leads me to think that redux's choice to make strict equal the default was perhaps justified.

I think you're right. And yeah, this would allow us to drop the shallowEqual function from the bundle. I like it but this would be a breaking change. I guess that's what semantic versioning is for. :)

**Comment by timkindberg** [comment]
Note: After reading what I wrote before hitting "Comment", I realized it's coming off as kind of entitled or presumptuous... sorry about that. I just sincerely want to share my feedback in hopes it might help. Listen or don't, I realize this is your project, not mine.

---

>Another thing i've noticed, people seem to just go for atomic picks, even if they know they can pick multiple items in one go.

Not at my company, we do multiple item selection almost exclusively at my work. 

I'm not super excited about adding `shallowEqual` as the 2nd arg everywhere. That seems a bit non-elegant; zustand has been so elegant otherwise. Importing my own equality function and passing it in... that's a decent amount of work on my part as a dev user. It's enough work where I'd rather just stop doing multiple item selection. If that's the case, just be opinionated and remove multiple item select all-together; otherwise it comes across as a tack-on feature and muddies the API.

From my own perspective, I'll probably try atomic selection and see how it feels. If zustand is still going to support mutliple item selection, I'd rather zustand figure it out which type of equality checking to use automatically or require a _small_ amount of work on my part to enable this (e.g. `create.shallow()` was a bit better IMO).

**Comment by drcmda** [comment]
tim, could you try atomic picks for a while and see how it's going?

the problem is that while it somewhat worked, it was also kind of broken, and if your store has larger objects, it will eventually affect performance, since it has to go through all props to figure out changes.

to make shallow equal a default wouldn't be much more than this:

```jsx
import create from 'zustand'
import shallowequal from 'shallowequal'

create.shallow = (...args) => {
  const [useStore, api] = createImpl(...args)
  return [sel => useStore(sel, shallowequal]), api]
}
```

though if we are shipping this bit, we'd have to ship shallowequal again, and it wouldn't treeshake like that.

**Comment by timkindberg** [comment]
Yes I think I will give atomic commits a try for a bit. Thank you for the response.

**Comment by drcmda** [comment]
i added a shallow export back to the lib, then it's at least more official looking than having to import some foreign equality function that either is battle tested or not - nobody knows. similar to redux, they ship it as well.

```jsx
import shallow from 'zustand/shallow'

const { foo, bar } = useStore(state => ({ foo: state.foo, bar: state.bar }), shallow)
```

**Comment by timkindberg** [comment]
I think that’s a good thing to provide and also thank you for the suggestion.

**Comment by timkindberg** [comment]
In my project at work, I upgrade zustand in a PR and it has been merged to master. Some other devs are noticing that their parts of the app are working differently with some bugs occurring.

They noticed that if they changed from object selection...
```js
import shallow from 'zustand/shallow'
const { foo, bar } = useMyStore(s => ({ foo: s.foo, bar: s.bar }), shallow)
```
...to atomic selection...
```js
const foo = useMyStore(s => s.foo)
const bar = useMyStore(s => s.bar)
```
... that the bugs went away.

**Question:** Do you expect those two snippets above to work identically in regards to how the component will behave and re-render?

**Comment by drcmda** [comment]
yes, they should be identical. is there something they could reproduce, would love to look into it.

**Comment by timkindberg** [comment]
Ok I'll see if we can boil it down to something reproducible

**Comment by dai-shi** [comment]
Sorry, I don't follow the discussion fully, but let close this as it's stale. Please open a new issue for further discussion.
