### ISSUE TITLE
Enhancement: Configure `storeName` and `actionName` in `devtools` middleware 

### ISSUE THREAD

**Issue by timkindberg** [react-spring/zustand#41]
I think it would be nice to supply a store "name" to the devtools middleware to more easily distinguish which store the "setState" actions are originating from.

API might be something like this:
```js
const [useStore] = create(devtools('ProductsStore', createFn))
```

Then in the Redux devtools you'd see:
```
@@INIT
ProductsStore setState()
```

As an added bonus, if there was someway to pass a name to each call to `set`, for example:
```js
const [useStore] = create(devtools('ProductsStore', (set) => ({
  actions: {
    loadProducts() {
      set('loadProducts', state => ({ products }))
    }
  }
})))
```

Then in the Redux devtools you'd see:
```
@@INIT
ProductsStore > loadProducts
```

It would probably be good if both functions could optionally take or omit the 1st string param without throwing an error, that way there is no penalty if you don't declare a store or action name.

**Comment by drcmda** [comment]
i've just added it, will push later, but it would be the 2nd argument to devtools, first is reserved for the store function, so: devtools(fn, prefix?: string)

**Comment by isakkeyten** [comment]
Is there a chance the second part of OPs request to be implemented?
~`set('loadProducts', state => ({ products }))`~
`set(state => ({ products }), 'loadProducts')`
> @@ INIT
ProductsStore > loadProducts

**Comment by drcmda** [comment]
you could do:

```jsx
(set, get, api) => ({
  dispatch: true,
  set: (name, args) => {
    set(args)
    api.devtools.send(api.devtools.prefix + 'someAction', get())
  },
  someAction: () => set({ xyz: 2 })
```

the dispatch this comes from this line: https://github.com/react-spring/zustand/blob/master/src/middleware.ts#L45 it checks if something called "dispatch" is there, or else it feeds setState calls into devtools.

**Comment by JeremyRH** [comment]
Why cant this be added to the [redux devtools middleware](https://github.com/react-spring/zustand/blob/345ef1fa026c1532f5d2cca6d47135180939cfc8/src/middleware.ts#L32)?
```ts
const initialState = fn(
  (args, name = '') => {
    set(args)
    if (name) api.devtools.send(prefix + name, get())
  },
  get,
  api,
);
```

**Comment by drcmda** [comment]
oh, that's even better - didn't think of that

**Comment by JeremyRH** [comment]
I added support for this in 2.0.0. @isakkeyten @timkindberg try it out whenever you have time.

**Comment by dai-shi** [comment]
Assuming this is resolved.
