### ISSUE TITLE
Discussion: Storing hooks in the state

### ISSUE THREAD

**Issue by timkindberg** [react-spring/zustand#42]
Is it good or bad to have hooks in your store state? It's a neat idea because you could move things like useEffect into there. My gut says "DO NOT DO THIS", but I wanted to share the thought. E.g.
```js
export const [useCommentsStore] = create((set, get) => ({
  comments: [],
  async useLoadComments(commentIds) {
    useEffect(() => {
      const commentIds = usersStore.getState().users[userId].commentIds
      set({ comments: await fetch(`/comments`, { ids: commentIds }) })
    }, [commentIds])
  }
}))
```
Then in a component:
```js
const Component = ({ commentIds }) => {
  const { comments, useLoadComments } = useCommentsStore()
  useLoadComments(commentIds)
  return <div>{ comments }</div>
}
```

However, I think it might be better to not couple the store to react via hooks usage. Just use hooks in the component instead like normal:
```js
const Component = ({ commentIds }) => {
  const { comments, loadComments } = useCommentsStore()
  useEffect(() => {
    loadComments(commentIds)
  }, [commentIds])
  return <div>{ comments }</div>
}
```

**Comment by drcmda** [comment]
At work we do store components in the store, basically everything goes, but in the end there has got to be a reason for doing it. If you struggle coming up with one, i wouldn't do it.

**Comment by JeremyRH** [comment]
I don't see a problem with having hooks in the state but I haven’t done that before.

In your example, the only way to load comments is through the hook. Let's say in the future you want to load comments when a user scrolls or clicks something. Now you have to add a `loadComments` function anyway and your hook will probably just call `loadComments` in `useEffect`. At that point `useLoadComments` would just be extra abstraction to save a few characters. In my opinion it's probably not worth it.

**Comment by dai-shi** [comment]
I would say it's not good in general, but it works as long as you don't violate rules of hooks. So, you can use the pattern with caution.

**Comment by yehonadav** [comment]
sometimes you want an action that would need a hook, or context, and in those cases, storing a hook that returns a function or an object would be very nice.

![image](https://user-images.githubusercontent.com/35917238/93710238-b8d14f00-fb4d-11ea-8a53-68f1b349ee71.png)

**Comment by dai-shi** [comment]
Hi, I don't see any issue in your snippet. Are you storing a hook in state?

----

As for the original issue, here's my current recommendation:

We don't intentionally document about storing hooks in Components or hooks, as it may confuse ordinary users.

The only valid use case I can think of is to lazy initialize a hook.

```js
import create from 'zustand'

const Component = () => {
  const useStoreRef = useRef()
  if (!useStoreRef.current) {
    useStoreRef.current = create(...)
  }
  const useStore = useStoreRef.current
  ...
}
```

You could use a state like:
```js
const useStore = useState(() => create(...))
```
but it involves unnecessary state. One might want to consider `useMemoOne` for shorthands.
