### ISSUE TITLE
zustand/shallow and zustand/middleware are not transpiled to cjs

### ISSUE THREAD

**Issue by timkindberg** [react-spring/zustand#46]
I'm getting errors because zustand/middleware.js and zustand/shallow.js have non-supported syntax in them. 

There is a .cjs.js file for each but then I have to import from 'zustand/middleware.cjs' which feels a bit weird, but it's a successful workaround.

It seems with additional non-main entries like these, they do not have the convenience of specifying `main` and `module` in the package.json like the main entry has. So the safest bet would probably be to have their `.js` file be the lowest common demoninator, commonjs.

I'm not sure these two entries need to be exported as anything but commonjs.

**Comment by drcmda** [comment]
that makes sense, i'll reconfigure rollup

**Comment by with-heart** [comment]
Can confirm that the `rollup` changes for this were completed in #65 and build outputs work as expected

**Comment by JeremyRH** [comment]
Great! Thank you for the feedback.
