### ISSUE TITLE
Question: How would you go about detecting mutations in the store

### ISSUE THREAD

**Issue by bernatfortet** [react-spring/zustand#51]
I'm trying to debug my application to make sure there's no mutation issues.
Back in redux days I could use a middleware to detect it.
Does anyone have any insights on how to add middleware to zustand to detect mutation issues?

**Comment by JeremyRH** [comment]
I believe this should work with redux dev tools:
```js
import create from "zustand";
import { devtools } from "zustand/middleware";

const [useStore] = create(
  devtools(set => ({
    count: 1,
    inc: () => set(state => ({ count: state.count + 1 })),
    dec: () => set(state => ({ count: state.count - 1 }))
  }))
);
```

Use zustand v1.0.7.
