### ISSUE TITLE
Integration with redux devtools?

### ISSUE THREAD

**Issue by dy** [react-spring/zustand#6]
Many developers consider that a deciding factor for choosing one or the other store solution.
Could you give an example how to integrate that?

**Comment by drcmda** [comment]
middleware could of course forward to the devtool api, but you are free to create functional actions without types, that leaves only the mutations/pre-state/after-state. unless of course you use a dispatch(type, ...args) reducer with a middleware around that.

**Comment by eranimo** [comment]
> you are free to create functional actions without types

It's fine to make that optional, but require it for redux devtools support.

**Comment by drcmda** [comment]
i thought about a middleware that injects dispatch and expects a typed signature. do you know an easy tutorial where i could learn how it integrate with redux devtools? i would give it a go ...

**Comment by eranimo** [comment]
The only way I can think of is if you implement a middleware for zustand that builds a redux store based on your zustand store, which can then be watched by the redux devtools

**Comment by drcmda** [comment]
i'll investigate a bit. sticking to a redux like structure would be easy - just haven't use redux devtools much.

**Comment by dy** [comment]
Here's an example integration for unistore: https://github.com/developit/unistore/blob/master/devtools.js

**Comment by drcmda** [comment]
got it working: https://twitter.com/0xca0a/status/1136037199533805573

works with action dispatchers and generic setState :)

**Comment by drcmda** [comment]
How do we publish this? @JeremyRH 

Should it be an export like

```jsx
import create from 'zustand'
import devtools from 'zustand/devtools'
import redux from 'zustand/redux'
```

And should the redux middleware be included, too? Or under another name?

**Comment by JeremyRH** [comment]
Yeah it looks like we can make it reasonably typesafe. Adding an extra file for people to import is the simplest solution but this doesn't scale well if you plan to add a lot of middlewares. Lots of middlewares would increase the package size (not bundle size, just the files you download when running `npm install zustand`) and slow the build and tests (if we add tests).

We could set up a mono-repo. I haven't done that before so it would be fun to learn even though it's not really necessary for a single middleware.

**Comment by drcmda** [comment]
As you wish, sounds good to me to take scaling into account. can't help you with monorepos, i have zero experience, but @aleclarson has just transformed react-spring into a monorepo, see https://github.com/react-spring/react-spring/pull/687 maybe he could answer questions you have

**Comment by JeremyRH** [comment]
Feature added with PR #38 
I think this is safe to close.
