### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by collegeimprovements** [react-spring/zustand#61]
Does `Zustand` support react-native as well ?

**Comment by drcmda** [comment]
yes, it should be cross platform, because all it uses are a couple of basic react hooks: useEffect, useLayoutEffect, useReducer, useRef.

**Comment by bnjmnjns** [comment]
Can confirm it works. Source: I'm currently using it in a production RN app I'm building :)
Remember you'll have to use at least React Native 0.59 as it requires hooks support.

**Comment by gabrielmoncea** [comment]
Even the persist api works :)
