### ISSUE TITLE
zombie children again 

### ISSUE THREAD

**Issue by drcmda** [react-spring/zustand#64]
![Screenshot 2019-10-03 at 16 19 32](https://user-images.githubusercontent.com/2223602/66135060-a1761a80-e5f9-11e9-9bb3-4dbb71d50e63.png)

example

```jsx
const [useStore, api] = create(set => ({
  sketch: { type: "sketch", children: ["1"] },
  "1": { type: "line", children: ["2", "3"] },
  "2": { type: "point", pos: [0, 0, 0] },
  "3": { type: "point", pos: [10, 0, 0] },
  delete() {
    console.log("------ setState ------")
    set(state => ({
      ...state,
      "1": { ...state["1"], children: ["3"] },
      "2": undefined
    }))
  }
}))

function Point({ id }) {
  console.log("    Point renders", id)
  const { pos } = useStore(state => state[id])
  return pos.join(" ")
}

function Line({ id }) {
  console.log("  Line renders", id)
  const ids = useStore(state => state[id].children)
  return ids.map(id => <Point key={id} id={id} />)
}

function Sketch() {
  console.log("Sketch renders")
  const ids = useStore(state => state.sketch.children)
  return ids.map(id => <Line key={id} id={id} />)
}

function App() {
  useEffect(() => void setTimeout(() => api.getState().delete(), 2000), [])
  return <Sketch />
}
```

live demo: https://codesandbox.io/s/crazy-frog-49vrj

### what happens 

    Sketch
      Line
        Point pos=[0,0,0]
        Point pos=[10,0,0]

The delete() method removed the first point and takes it out of its parents children collection. React normally renders hierarchical, so it should be fine. But for some weird reason each listener in zustand immediately goes to the components render function. It actually calls a useReducer/forceUpdate, which then triggers reacts dispatchAction > scheduleWork > requestWork > performSyncWork ... > render

```jsx
const setState: SetState<TState> = partial => {
    const partialState =
      typeof partial === 'function' ? partial(state) : partial
    if (partialState !== state) {
      state = Object.assign({}, state, partialState)

      //<--- the next line causes synchroneous render passes for each listener called
      listeners.forEach(listener => listener())
    }
  }
```

I've tried to wrap it into batchedpdates and that seemed to fix it, now React renders in hierarchical order again, **after** the listeners have been triggered:

```jsx
      unstable_batchedUpdates(() => {
        listeners.forEach(listener => listener())
      })
```

Is there any explanation for this? And what can we do to fix it?

@JeremyRH

**Comment by drcmda** [comment]
update, unstable_batchedUpdates isn't really a fix, because it's tied to a single reconciler. it goes into the same problem again in a react-three-fiber canvas for instance, which is another reconciler. :-S

**Comment by JeremyRH** [comment]
@drcmda Thanks for the detailed information.

#65 fixes the broken example but I'm not sure if it covers all cases. Also I'm not sure if there are unknown side effects with this fix.
