### ISSUE TITLE
subscribe type error since version 2.x

### ISSUE THREAD

**Issue by lunika** [react-spring/zustand#67]
Hi,

I upgraded this morning zustand from version `1.0.7` to version `2.1.0` and I have a typescript compilation error.
First I had to change the syntax with the new `subscribe` API. Before I has this:

```typescript
import create from 'zustand';

interface State {
  time: number;
  setTime: (time: number) => void;
}

export const [useTranscriptTimeSelector, useTranscriptTimeSelectorApi] = create<
  State
>(set => ({
  setTime: time => set({ time }),
  time: 0,
}));

useTranscriptTimeSelectorApi.subscribe(
    time => (player.currentTime = time as number),
    {
      selector: state => state.time,
    },
  );
```

Now with the new syntax I have:

```typescript
import create from 'zustand';

interface State {
  time: number;
  setTime: (time: number) => void;
}

export const [useTranscriptTimeSelector, useTranscriptTimeSelectorApi] = create<
  State
>(set => ({
  setTime: time => set({ time }),
  time: 0,
}));

  useTranscriptTimeSelectorApi.subscribe(
    time => player.currentTime = time,
    state => state.time,
  );
```

And I have this error message:

```
error TS7006: Parameter 'time' implicitly has an 'any' type.

      time => player.currentTime = time,
       ~~~~
```

If I refer to the readme, my syntax is good.

Thank you for your help.

**Comment by JeremyRH** [comment]
It seems you will have to explicitly set the type of `time` in this case:
```ts
useTranscriptTimeSelectorApi.subscribe(
  (time: number) => player.currentTime = time,
  state => state.time,
);
```

Why?
`api.subscribe` uses the same generic (`T`) for the listener's parameter and the return type of the second argument:
```ts
// Simplified
function subscribe<T>(
  listener: (value: T) => void,
  selector: (state: State) => T
)
```

Types are usually inferred left-to-right. It attempts to infer `(value: T)` first and fails because you did not provide a type in your listener. That would be fine because it then looks at the return type of the selector to get the type. Unfortunately, it fails again because the return type of the selector involves another generic that has not been inferred yet.

I think you can also do this:
```ts
useTranscriptTimeSelectorApi.subscribe(
  time => player.currentTime = time,
  () => useTranscriptTimeSelectorApi.getState().time,
);
```
This should work because the return type of the selector does not depend on the type of the argument passed into it.

**Comment by lunika** [comment]
Hi,

thanks for your reply but I already tried all your proposition and unfortunately I still have error this is why I opened this issue, I didn't find a solution.

When I try this solution:

```typescript
useTranscriptTimeSelectorApi.subscribe(
  (time: number) => player.currentTime = time,
  state => state.time,
);
```

I have this error message:

```
Player/createPlyrPlayer.ts:99:5 - error TS2345: Argument of type '(time: number) => number' is not assignable to parameter of type 'StateListener<unknown>'.
  Types of parameters 'time' and 'state' are incompatible.
    Type 'unknown' is not assignable to type 'number'.

99     (time: number) => player.currentTime = time,
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Player/createPlyrPlayer.ts:100:5 - error TS7006: Parameter 'state' implicitly has an 'any' type.

100     state => state.time,
        ~~~~~
```

And when I try this solution:

```typescript
useTranscriptTimeSelectorApi.subscribe(
  time => player.currentTime = time,
  () => useTranscriptTimeSelectorApi.getState().time,
);
```

I have the same initial error:

```
Player/createPlyrPlayer.ts:99:5 - error TS7006: Parameter 'time' implicitly has an 'any' type.

99     time => player.currentTime = time,
       ~~~~
```

**Comment by lunika** [comment]
The project I'm working on is open-source if maybe you want more code. Where the subscriber is implemented is here: https://github.com/openfun/marsha/blob/03877c38123b0ffbd719b4b8114eeb5fe87a8a35/src/frontend/Player/createPlyrPlayer.ts#L98-101

And where the zustand store is defined is here https://github.com/openfun/marsha/blob/03877c38123b0ffbd719b4b8114eeb5fe87a8a35/src/frontend/data/stores/useTranscriptTimeSelector/index.tsx

**Comment by JeremyRH** [comment]
Thanks, I think I see the issue. I should have a fix for this soon.

**Comment by lunika** [comment]
Thanks, now I have a new error but I think I can deal with it.

**Comment by JeremyRH** [comment]
Is the new error unexpected or improper? The listener should have the signature:
```ts
(state: T | null, error?: Error) => void
```
This is because it's possible for the listener to be called with an error. This means you should have a guard for the state possibly being `null`.
