### ISSUE TITLE
Persistency

### ISSUE THREAD

**Issue by dy** [react-spring/zustand#7]
Redux or unistore have redux-persist or unissist persistency solution. Is there any persistor for zustand? Mb that can be solved with simple throttled middleware?

**Comment by drcmda** [comment]
Middleware has full access to initial state and mutations, storage based or remote persist middleware wouldn't be hard to create.

**Comment by JeremyRH** [comment]
I'm going to close this issue. We can add more middleware examples at a later time if we feel the need.
