### ISSUE TITLE
devtools broken

### ISSUE THREAD

**Issue by joelmoss** [react-spring/zustand#72]
Using 2.2.0 and the `devtools` middleware is broken due to an incorrect guard going from [this](https://github.com/react-spring/zustand/pull/65/files#diff-e97e9c0e2b7d59ae0cb671be17b1c976L47) to [this](https://github.com/react-spring/zustand/pull/65/files#diff-e97e9c0e2b7d59ae0cb671be17b1c976R50)

You now have this...

```javascript
!initialState.dispatch && ignoreState && 'setState'
```

when it should be this...

```javascript
!initialState.dispatch && !ignoreState && 'setState'
```

**Comment by drcmda** [comment]
must've happened by accident, will flip it. @JeremyRH or was this intentional?

**Comment by JeremyRH** [comment]
I think it was an accident. Sorry about that.

**Comment by drcmda** [comment]
i published a patch

**Comment by joelmoss** [comment]
thx guys
