### ISSUE TITLE
Middleware in TypeScript

### ISSUE THREAD

**Issue by alexluong** [react-spring/zustand#75]
Hi, I'd like to use `zustand` with TypeScript. Any chance you can write the example middlewares (`log` and `immer`) with TypeScript so I can follow and imitate?

I'd really appreciate it. Thank you. @JeremyRH @drcmda.

**Comment by JeremyRH** [comment]
I like that the examples are plain JS, it makes them more accessible. I also don't want to add too much noise to the readme. Maybe we can provide a link to the [typescript playground](http://www.typescriptlang.org/play/) alongside the examples.

**Comment by alexluong** [comment]
@JeremyRH I agree that plain JS is very accessible to everybody. However, when writing middleware, I'm not sure how to properly type things. Therefore, I'd love an example here, even if it's not gonna make it to the doc itself.

For example:

```js
const log = config => (set, get, api) => config(args => {
  console.log("  applying", args)
  set(args)
  console.log("  new state", get())
}, get, api)
```

What are `config`, `set`, `get`, `api` types? Not that it's breaking anything, but I'd love to properly type my middleware.

Thanks!

**Comment by JeremyRH** [comment]
Ah sorry, I misunderstood you. The types are exported so you can use them:
```ts
import create, { StateCreator, SetState, GetState, StoreApi } from 'zustand'

interface YourState {
  a: number,
  b: string
}

const log = (config: StateCreator<YourState>) => (
  set: SetState<YourState>,
  get: GetState<YourState>,
  api: StoreApi<YourState>
) => config(args => {
  console.log("  applying", args)
  set(args)
  console.log("  new state", get())
}, get, api)
```

**Comment by coffee-cup** [comment]
I have found this middleware type useful

```ts
type Middleware<S> = (
  config: StateCreator<S>,
) => (set: SetState<S>, get: GetState<S>, api: StoreApi<S>) => S;

const log: Middleware<StoreType> = config => (set, get, api) =>
  config(
    args => {
      set(args);
      console.log("new state", get());
    },
    get,
    api,
  );
```

**Comment by alexluong** [comment]
Thank you! This is really helpful.

**Comment by kurosh-z** [comment]
@JeremyRH 
hey !
how to write types when use it with immer ?

I defined types like:
```typescript
interface IState {
  currentGroup: object | null;
  GroupIndex: number;
  palying: boolean;
}

const myStore = (set: SetState<IState>) => ({
  currentGroup: null,
  GroupIndex: 0,
  playing: false,

  setCurrentGroup: (group: object) =>
    set((state) => {
      state.currentGroup = group;
    })
});

const immer = (config: StateCreator<IState>) => (
  set: SetState<IState>,
  get: GetState<IState>,
  api: StoreApi<IState>
) => config((fn) => set(produce(fn)), get, api);

export const useStore = immer(myStore);
```
<img width="808" alt="Screen Shot 2020-08-31 at 11 46 38 PM" src="https://user-images.githubusercontent.com/32224317/91772049-5fc46a00-ebe4-11ea-8d1f-4e4cd7986d5e.png">

<img width="976" alt="Screen Shot 2020-08-31 at 11 47 20 PM" src="https://user-images.githubusercontent.com/32224317/91772047-5dfaa680-ebe4-11ea-8e8b-97b5e2b057ab.png">


sandbox: https://codesandbox.io/s/pedantic-flower-immerzustand-rh070?file=/src/App.tsx:196-713

**Comment by dai-shi** [comment]
@kurosh-z Hey, I fixed it recently. Please check the example in #169. If it doesn't work, would you please file a new issue?

**Comment by danielrotaermel** [comment]
Thank you @coffee-cup! I had to use: type Middleware<S **extends State**> to make it work

> I have found this middleware type useful
> 
> ```ts
> type Middleware<S extends State> = (
>   config: StateCreator<S>,
> ) => (set: SetState<S>, get: GetState<S>, api: StoreApi<S>) => S;
> 
> const log: Middleware<StoreType> = config => (set, get, api) =>
>   config(args => {
>     console.log("  applying", args)
>     set(args)
>     console.log("  new state", get())
> }, get, api);
> ```

**Comment by savissimo** [comment]
> I have found this middleware type useful
> 
> ```ts
> type Middleware<S> = (
>   config: StateCreator<S>,
> ) => (set: SetState<S>, get: GetState<S>, api: StoreApi<S>) => S;
> 
> const log: Middleware<StoreType> = config => (set, get, api) =>
>   config(args => {
>     console.log("  applying", args)
>     set(args)
>     console.log("  new state", get())
> }, get, api);
> ```

Sorry, what is `StoreType`?

**Comment by petertoth-dev** [comment]
> > I have found this middleware type useful
> > ```ts
> > type Middleware<S> = (
> >   config: StateCreator<S>,
> > ) => (set: SetState<S>, get: GetState<S>, api: StoreApi<S>) => S;
> > 
> > const log: Middleware<StoreType> = config => (set, get, api) =>
> >   config(args => {
> >     console.log("  applying", args)
> >     set(args)
> >     console.log("  new state", get())
> > }, get, api);
> > ```
> 
> Sorry, what is `StoreType`?

@savissimo I believe that's your whole store's custom type. For example if your store looks like this {foo: 1, bar: 'yo'} your `StoreType` is 

```
export interface StoreType {
    foo: number,
    bar: string
}
```
