### ISSUE TITLE
[devtools] doesn't log actions since v2

### ISSUE THREAD

**Issue by pzi** [react-spring/zustand#77]
When updating from 1.0.7 to 2.2.1, I lose the tracking of all actions in the Redux devtools:

## 2.2.1
![image](https://user-images.githubusercontent.com/2037851/68097209-a2e47c80-fef0-11e9-9495-0830ef579b87.png)

## 1.0.7
![image](https://user-images.githubusercontent.com/2037851/68097276-1b4b3d80-fef1-11e9-89db-4f67f84c5867.png)

The app works just fine and the store updates correctly when using the app, it just doesn't log out the commits any more.

Using it like:

```ts
import create, { StateCreator } from 'zustand'
import { devtools } from 'zustand/middleware'

export const DefaultStoreState: DefaultStateGetters = {
  lastDataUpdate: new Date(),
  loading: false,
  showDrawer: false,
  message: null,
  ...
}

const store: StateCreator<DefaultState> = (set, get) => ({
  ...DefaultStoreState,
  ...
})

export const [useStore, Store] = create<DefaultState>(devtools(store, 'WACHS App Store'))
```

Any pointers would be appreciated. Let me know if you need more detail and I will update this post.

Cheers & thanks
Patrik

**Comment by vuhg** [comment]
Hey @pzi, 

As you can see on the line https://github.com/react-spring/zustand/blob/master/src/middleware.ts#L33, you need to put `name` of your function that you want to track in Redux dev tools.

For example:
```javascript
const [useStore] = create(devtools(set => ({
  count: 1,
  inc: () => set(state => ({ count: state.count + 1 }), 'inc'),
  dec: () => set(state => ({ count: state.count - 1 }), 'dec')
})))
```

I had the same problem too! Hope this help.

**Comment by pzi** [comment]
thanks for the suggestion @vuhg, however, it seems that the types in typescript are not up-to-date as it's complaining about `set` only accepting 1 argument, not 2.

![image](https://user-images.githubusercontent.com/2037851/68466390-45816000-024f-11ea-90d3-50eec1b3b5cc.png)

**Comment by drcmda** [comment]
do you know what types it would need? im still struggling with TS. i can update and cut a release to fix this.

**Comment by vuhg** [comment]
Yeah, you need to update `set`'s signature in [middleware ](https://github.com/react-spring/zustand/blob/master/src/middleware.ts#L15)or [index](https://github.com/react-spring/zustand/blob/master/src/index.ts#L14).

**Comment by vuhg** [comment]
Can you try this this @pzi:

```ts
import create, { State, PartialState } from './zustand'
import { devtools } from './zustand/middleware'

type NamedSetState<T extends State> = (partial: PartialState<T>, name?: any) => void

interface Count {
  count: number
}

const [useStore] = create<Count>(devtools((set: NamedSetState<Count>) => ({
  count: 1,
  inc: () => set((state: any) => ({ count: state.count + 1 }), 'inc'),
  dec: () => set((state: any) => ({ count: state.count - 1 }), 'dec')
})));
```

@drcmda, should we export this in middleware.ts
```ts
export type NamedSetState<T extends State> = (partial: PartialState<T>, name?: any) => void
```

**Comment by drcmda** [comment]
i guess, would you make the PR?

**Comment by vuhg** [comment]
Hey drcmda, i'm struggling with TS too  😅 . 
I can't get `(partial: PartialState<T>, name: any = "action")` fallback.

This is popular library (can affect a lot of devs) so i think it better to wait for some TS expert helping us here.

**Comment by pzi** [comment]
Yeah with the type override it works :) Will use that for now. thanks

**Comment by pzi** [comment]
I was considering submitting a PR to change the following line: 

`const namedSet = (state: any, name?: any)`

in https://github.com/react-spring/zustand/blob/master/src/middleware.ts#L33 to

`const namedSet = (state: any, name: any = 'action')`

but that would mean it would always log for to devtools for everyone. Unsure if that's desired?

**Comment by drcmda** [comment]
@JeremyRH what do you think?

**Comment by JeremyRH** [comment]
@pzi Your issue `Expected 1 argument but got 2` is caused by this:
```ts
const store: StateCreator<DefaultState>
```
The `StateCreator` type shouldn't be used with the middleware's `devtools` function.
Try this:
```ts
type DevToolsStateSetter<T> = (partial: PartialState<T>, name?: string) => void

const store = (
  set: DevToolsStateSetter<DefaultState>,
  get: GetState<DefaultState>
): DefaultState => ({
  ...DefaultStoreState,
  ...
})
```

We should export a `DevToolsStateCreator` type in middleware to solve this. We should also default `name` to `'action'` like you said.

**Comment by aaronmfrancis** [comment]
For anyone who comes here looking for a quick fix, my solution was to make a type based on the normal StateCreator:

```ts
import { State, StateCreator } from 'zustand';

/** To allow named functions when using devtools */
type StateCreatorDev<T extends State> = (
  set: Parameters<StateCreator<T>>[0] & { name?: string },
  get: Parameters<StateCreator<T>>[1],
  api: Parameters<StateCreator<T>>[2]
) => T;
```

**Comment by isakkeyten** [comment]
Can we get this in the docs?

**Comment by MillerGregor** [comment]
I followed the naming suggestions in this thread, but was still not seeing actions.
I found a quick fix... see PR #117

**Comment by dai-shi** [comment]
Does anybody know what's the status of this issue?

**Comment by sanojsilva** [comment]
Hey @dai-shi,

@vuhg Solution works. But however, if we use immer we have to pass args like below otherwise it will not show state updates in the dev tools.

```js
const immer = (config) => (set, get, api) =>
  config((fn, args) => {
	// args equals to the name we passed to the function in our store ("SET_CART_OPEN", "SET_BACKDROP_OPEN")
    return set(produce(fn), args), get, api;
  });

const [useStore] = create<Store>(
  devtools(
    immer((set) => ({
      cart: {
        open: false,
        setOpen: (value) =>
          set((state) => {
            if (typeof value !== "undefined") {
              state.cart.open = value;
            } else {
              state.cart.open = !state.cart.open;
            }
          }, "SET_CART_OPEN"),
      },
      backdrop: {
        open: false,
        setBackdropOpen: (value) => {
          set((state) => {
            state.backdrop.open = value;
          }, "SET_BACKDROP_OPEN");
        },
      },
    }))
  )
);

```

**Comment by dai-shi** [comment]
@vuhg Thanks for the note. Let me read the thread again.

So, the issue can be divided into three pieces, correct?

1) `namedSet` should have default name
2) TS type in `devtools` doesn't allow adding set names.
3) Typing with immer middleware needs a workaround

BTW, I have some questions about typing with immer. #96

**Comment by dai-shi** [comment]
v3 has `replace` flag in the second argument. we need to find a better way for the devtools middleware. cc @drcmda

**Comment by dai-shi** [comment]
Now v3 is out, We need to fix this. Does anyone have ideas?

**Comment by WhiteCollarParker** [comment]
Very helpful issue thread! Saved me some hours

**Comment by dai-shi** [comment]
I think I fixed it fully. #167
