### ISSUE TITLE
[FR] More idiomatic solution for adding/removing state-dependent event listeners

### ISSUE THREAD

**Issue by universse** [react-spring/zustand#79]
Recently I have a use case where I need to add event listener in response to state change, using `subscribe`. Currently there is no idiomatic way to remove those listeners.

Currently I'm doing it like so, but it doesn't feel right.

```js
let listener
subscribe(
  someState => {
    window.removeEventListener('click', listener)
    
    listener = () => console.log(someState)
    
    window.addEventListener('click', listener)
  },
  selector
```

I guess an API similar to React's `useEffect` with cleanup function would do the trick?

This also applies to `setInterval` and `setTimeout`.

**Comment by drcmda** [comment]
state doesn't have lifecycles though, like a component that gets mounted/unmounted. i wonder what you would suggest, do you have any idea how that would go?

**Comment by universse** [comment]
I'm not entirely sure it's about lifecycles. In my mind, both React's `useEffect` and zustand's `subscribe` can be seen as side effects as a result of a change in state.

```js
useEffect(
  () => {
    // do something when stateA or stateB changes
  },
  [stateA, stateB]
)
```

```js
subscribe(
  ([stateA, stateB]) => {
    // similarly
    // do something when stateA or stateB changes
  },
  state => [state[stateA], state[stateB]] // kinds of similar to useEffect's deps array
)
```

So my suggestion would be allowing `subscribe` to return a cleanup function, just like `useEffect`. Something along the line of

```js
subscribe(
  ([stateA, stateB]) => {
    const listener = () => console.log(a, b)

    window.addEventListener('click', listener)

    return () => {
      window.removeEventListener('click', listener)
    }
  },
  state => [state[stateA], state[stateB]] // kinds of similar to useEffect's deps array
)
```

**Comment by drcmda** [comment]
`state => [state[stateA], state[stateB]]` would only work if you add `, shallow)` in the end, but that aside, let me think about it for a while. 

@JeremyRH what's your opinion?

**Comment by JeremyRH** [comment]
@universse When would Zustand run the cleanup function? There is an `unsubscribe` function that `subscribe` returns. We could put it in there but you have to call unsubscribe on your side anyway.

**Comment by universse** [comment]
Yes I want it to run when state changes. On the other hand, unsubscribing would prevent further addition of event listeners.

Thanks for the sample solution. Perhaps it can be extracted to a middleware. Thus, there's no need to include it in core.

```js
function cleanUp(listener) {
  let cleanup

  return (...args) => {
    if (typeof cleanup === 'function') {
      cleanup()
    }
    cleanup = listener(...args)
  }
}

function withEffect(initial) {
  return (set, get, api) => {
    api.runEffect = (listener, ...rest) =>
      api.subscribe(cleanUp(listener), ...rest)

    return {
      ...initial,
    }
  }
}

const [useStore, { runEffect }] = create(withEffect({ todos: [] }))

runEffect(
  todos => {
    const listener = () => console.log(todos)

    window.addEventListener('click', listener)

    return () => {
      window.removeEventListener('click', listener)
    }
  },
  state => state.todos
)
```

**Comment by dai-shi** [comment]
Is it resolved? Please file a new issue for further discussion.
