### ISSUE TITLE
Immer + Typescript - produce state type is missing

### ISSUE THREAD

**Issue by ranihorev** [react-spring/zustand#83]
I'm trying to use immer to simplify the process of updating nested state. However, the `state` object is converted to `any` within the produce function. Am I doing something wrong?

Example: 

```
interface State {
  papers: {name: string; id: string}[];
}

const stateAndActions = (set: NamedSetState<State>, get: GetState<State>) => {
  return {
    ...initialState,
   updatePaper: (id: string, name: string) => set(produce(state => {<do something here>})),
  }
}
```

p.s. I just switched from redux to zustand and I love it!

**Comment by JeremyRH** [comment]
Can you show the type for `NamedSetState`?

**Comment by ranihorev** [comment]
`export type NamedSetState<T extends State> = (partial: PartialState<T>, name?: any) => void;`

**Comment by JeremyRH** [comment]
Unfortunately I think this is a problem with immer's produce. [It is possible to infer the state object](http://www.typescriptlang.org/play/?ssl=5&ssc=2&pln=3&pc=1#code/C4TwDgpgBACghgJ2ASzgGwMrDsCGLC4IA8AKgHxQC8UAFAOYFY4QBcdAztru6QJTVK8JKjRlyAqpQBuAe2QATANwAoFaEhRmualADeKqEagAzWbPZcEyAHb0VAXzUmArjYDGKWTahgEshRd3CHFadwAjdlouFl5JGXkFAQNjKAQCFwQfaO42KH5BfUNU43dvLigysBBdPSgAOkaYnQdVEtLwsNlqvjb2tIysyu6QPqNWx2c3T2RvSvSWLFl06IJ2YRR0bTwCImJtiSLUjgJaPwCgiByWQpT+5oh6s1ldACJwxFexqAc+XscgA) but immer's types are more complicated.

I know it's a pain, but you can define the type in the produce callback: `set(produce(state: State) => ...`.

**Comment by ranihorev** [comment]
Thanks!
That's actually not that bad :)

**Comment by s97712** [comment]
I created a produce that can deduce the state.

```ts
export function make<T>(cb: (value: Draft<T>) => void): (value: T) => T {
  return produce(cb)
}
```
