### ISSUE TITLE
const { value, setValue } = useStore(), value: any / setValue: any?

### ISSUE THREAD

**Issue by Pirastrino** [react-spring/zustand#87]
Hi, so I have simple store defined like this:

```javascript
import create from 'zustand';

const [useStore] = create(set => ({
  value: 'char', // <- I'd like this to be an enum (e.g. 'char' | 'num')
  setValue: (e: MouseEvent, newValue: string) => set(state => ({ value: newValue })),
}));

export { useStore };
```
Then when I use the store in some component, lets say:

```javascript
const { value, setValue } = useStore(); // <- ts says const value: any, const setValue: any

return (
  <Button onClick={e => setType(e, 'num')} />
)
```

How can I ensure that `setType()` is called only with correct string `'char' | 'num'`?

Anyway I am new to the typescript and React so bear with me please.
I also tried useContext from React itself but your api is just so easy to use, so I want to thank you for this library and your work as well, keep it up!

**Comment by acd02** [comment]
Hello :)

Take a look at this [sandbox](https://codesandbox.io/s/sparkling-rgb-jr7gg), I hope it will help you understand how to type your store properly.

Basically, you define your `Store` shape and then you pass it to the `create`function when you call it:
```ts
type Enum = 'char' | 'num'
type Store = {
  value: Enum
  setValue: (newValue: Enum) => void
}
const [useStore] = create<Store>(set => ({
  value: 'char',
  setValue: newValue => set({ value: newValue })
}))
```
