### ISSUE TITLE
Batch setState

### ISSUE THREAD

**Issue by ecrona** [react-spring/zustand#89]
Hello!

I'm reviewing this store library, testing out some quirks and stuff. It seems really great, but I would suggest adding some type of batch update when updating multiple stores, if it doesn't already exist.

```js
// actions
export const action = () => {
  modalStoreApi.setState({ show: false });
  usersStoreApi.setState({ users: [ ...usersStoreApi.getState().users, 'new user' ] })
}

// component
export const Component = () => {
  const show = useModalStore(store => store.show)
  const users = useUsersStore(store => store.users)

  return show && <span>User 1: {users[0]}</span>
})
```

So in this case, the component will re-render twice, so what would be cool would be something like this, similar to how redux-thunk does it:

```js
// actions
export const action = () => {
  batch(() => {
    modalStoreApi.setState({ show: false });
    usersStoreApi.setState({ users: [ ...usersStoreApi.getState().users, 'new user' ] })
  })
}
```

Not the greatest example perhaps, but I know this is needed at times, when you're separating your stores, and combining them at places using selectors and so on.

What do you think?

Thanks

**Comment by drcmda** [comment]
I wouldn't bother, only legacy react doesn't batch, blocking and concurrent will batch automatically, see: https://reactjs.org/docs/concurrent-mode-adoption.html#feature-comparison

Meanwhile, use a small middleware:

```jsx
import { unstable_batchedUpdates } from 'react-dom'

const batched = config => (set, get, api) =>
  config(args => unstable_batchedUpdates(() => set(args)), get, api)
```

**Comment by ecrona** [comment]
That seems very cool, I've actually just tried it but it doesn't seem to work.

I updated react & react-dom to experimental, I tried setting the root node with `ReactDOM.createBlockingRoot` and `ReactDOM.createRoot` but React still rendered twice, or at least the components ran my console.log statement twice, it even started rendering everything twice even if I just did a single update.

Maybe I did something wrong, or this library isn't ready for concurrent mode, or concurrent mode just isn't stable enough yet.

**Comment by drcmda** [comment]
async will run next frame. i dont think that redux with thunks will execute two async calls the same frame. it's also just using plain batchedUpdates.

**Comment by ecrona** [comment]
So you're saying setState is async? In redux dispatching actions is not async, we're running an async action waiting for e.g. an api call, but once that's been received, we can dispatch 2 synchronous state-changes using batch, and then redux will propagate changes to the UI components, hence only one rerender.

This would be nice.

**Comment by drcmda** [comment]
No but if you have an action that is async it will run next frame, same as a thunk. At work we use batched Middleware as well for a legacy react project and it's going well. But async actions, at least in my opinion, can not be batched, or at least I wouldn't expect it.

**Comment by ecrona** [comment]
Hmm, I'm confused. As I see it, the async action will await a request for instance, then dispatch two store-changes, then I'd want it to re-render affected components. So yes, it will run it the next frame, but it would be nice to batch ALL of the changes in the next frame.

Maybe I could create some batch middleware as well.

**Comment by rdhox** [comment]
> or at least the components ran my console.log statement twice

Don't trust your console.log to check rerender. Your component is a function, and functions are always execute, it do not means that React actually triggered an update for your component. 

You can check that a render occur with a `Math.random()`: 

```js
return(
  {...some JSX}
  {Math.random()}
);
```

**Comment by ecrona** [comment]
So how do I know if it rendered once or twice? The Math.random() will be updated in either case. IMO it's not the end of the world to render twice, but I think it's unnecessary to even call the component at any rate of synchronous state changes.

**Comment by rdhox** [comment]
If you see the number generate by `Math.random()` changing when there is no reason for your component to render, it means it renders when it shouldn't. It's not dramatic as long as you don't have 20 components that make calculation on your interface. 
You can use this library: https://github.com/welldone-software/why-did-you-render
to check on your useless render. But don't get to paranoid over rerender, as long as you don't feel the interface going slow, it means it's working good :)

**Comment by ecrona** [comment]
So the Math-random thing is not to see how many times it re-renders, simply to see if it's ... rendering fast?

Sure yeah, I would probably still be interested in using this lib even if it does one or two unnecessary re-renders, however, what if I have a heavy-logic computing selector hook, which is using nodes 6-7 different stores to compute one value, and in some case I would update all of these store nodes used in the selector, then the selector hook would calculate 6-7 times. That seems unnecessary.

Sure I could use effect-hooks and stuff, but if one of my nodes are deep nested objects I'd have to create some advanced equivalence-checker or so. It just feels simpler to batch the updates and call the listeners once the batch is completed.

**Comment by rdhox** [comment]
>So the Math-random thing is not to see how many times it re-renders, simply to see if it's ... rendering fast?

If the number change, it means a rerender happened. What do you mean by "rendering fast" ?

**Comment by ecrona** [comment]
> > So the Math-random thing is not to see how many times it re-renders, simply to see if it's ... rendering fast?
> 
> If the number change, it means a rerender happened. What do you mean by "rendering fast" ?

Maybe I misunderstood, but why would it help me to see if it rendered or not, when I'm trying to resolve whether it rendered once, or twice? The rendering happens to fast for me to see if the number changes twice, so the only thing this will do is help me see if it rendered. But I know that it renders, I want to know if it renders twice.

**Comment by dai-shi** [comment]
Let me close this as the discussion seems stale. Please file a new issue for further discussion.

**Comment by joshsten** [comment]
> That seems very cool, I've actually just tried it but it doesn't seem to work.
> 
> I updated react & react-dom to experimental, I tried setting the root node with `ReactDOM.createBlockingRoot` and `ReactDOM.createRoot` but React still rendered twice, or at least the components ran my console.log statement twice, it even started rendering everything twice even if I just did a single update.
> 
> Maybe I did something wrong, or this library isn't ready for concurrent mode, or concurrent mode just isn't stable enough yet.
> 
> Edit: I also tried the batched-middleware thing with the same result :/
> Edit2: With batched-middleware and React-DOM 16.12 (latest stable) it seems to work with synchronous function calls, but as long as I make an async call, and then update 2 stores, it renders twice again

`import { batchedSubscribe } from "redux-batched-subscribe";
import raf from "raf";

// Batcher see https://github.com/tappleby/redux-batched-subscribe/issues/11#issuecomment-264701480
let rafID;
function rafUpdateBatcher(notify) {
	if (rafID) return;
	rafID = raf(() => {
		rafID = null;
		notify();
	});
}`

Then use it with:

`isBrowser ? batchedSubscribe(rafUpdateBatcher) : f => f`

Instead of using `unstable_batchedUpdates`

This may get the behavior you are looking for, and is what we use.
