### ISSUE TITLE
[devtools] get name of caller in middleware

### ISSUE THREAD

**Issue by VinSpee** [react-spring/zustand#92]
Hi!

I've been working on a port to zustand which contains a substantial analytics middleware. In the meantime, I learned a few things - is my understanding correct here?

1. the `devtools` middleware requires `name` as a second parameter to all of your `set` functions, which it then sends to redux devtools.
2. the `devtools` middleware doesn't continue passing those `name`s along, it just drops them
3. in order to use the names elsewhere, I must put the devtools middleware _last_.
4. each middleware prior must also be sure to pass `name` along.

If I'm understanding this correctly, I'm curious as to if there might be a better way to pass the name of the `set` function which has caused this middleware to be fired.

For (__ugly__) example:

```ts
function caller(): string {
  return new Error().stack
    .match(/at (\S+)/g)[3]
    .slice(3)
    .replace('Object.', '');
}

export const middleware = store => (set, get, api) =>
  store(
    (getPayload: any) => {
      const name = caller();
      const payload = getPayload();
      const state = get();

      switch(name) {
        case 'onReady': {
          sendAnalyticEvent(payload);
        }
        default: {}
      }
      return set(getPayload);
    },
    get,
    api,
  );

```

Is there any path to a _sane_ API for this which would solve a couple of problems?

1. no need to pass "name" as a 2nd setter param for redux devtools
2. access to the name of the caller from any middleware

Thanks! Great work on zustand.

**Comment by drcmda** [comment]
sounds interesting, do you have any ideas? you can take a look - the middleware isn't that complicated. i would be glad to drop the necessity for the 2nd arg if there's a better way

**Comment by VinSpee** [comment]
"better" is the tricky part here I think, as [`caller` is deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller). The hack above "works" in userland. I'm going to think a bit on how core might expose something more stable in its place

**Comment by dai-shi** [comment]
Let me mark as duplicated with #77. Please merge the discussion there.
