### ISSUE TITLE
Component cann't get newstate.

### ISSUE THREAD

**Issue by aniiantt** [react-spring/zustand#93]
When I use it like this, component cann't get newstate.
```
const fooSelector = useCallback(state => state.foo, [])
const foo = useStore(fooSelector)
```
I think it's because of this line of code: https://github.com/react-spring/zustand/blob/master/src/index.ts#L132
```
    if (
      subscriber.selector !== selector ||
      subscriber.equalityFn !== equalityFn ||
      subscriber.errored
    ) {
      // Using local variables to avoid mutations in the render phase.
      newStateSlice = selector(state)
      hasNewStateSlice = !equalityFn(subscriber.currentSlice, newStateSlice)
    }
```
`usecallback` caused the selector not to be updated. So even if the state is updated, it doesn't compare the new state with the old state.So components and data are not updated.

**Comment by JeremyRH** [comment]
Can you show a codepen example? How are you updating the state?

**Comment by aniiantt** [comment]
> Can you show a codepen example? How are you updating the state?

Ok, I was wrong, but the problem remains.
https://codesandbox.io/s/heuristic-sea-zjn0x

**Comment by JeremyRH** [comment]
That example is only wrapping `set`. It is possible to wrap both if you wrap `create`:
```js
const immer = config => (set, get, api) => config(fn => set(produce(fn)), get, api);
const createImmerStore = createState => {
  const [useStore, api] = create(immer(createState));
  const setState = api.setState;
  api.setState = fn => setState(produce(fn));
  return [useStore, api];
};

// Don't call: immer(set => ...
// `set` will already be wrapped by `createImmerStore`.
const [useStore, userStoreApi] = createImmerStore(set => ({
  foo: {
    bar: 1
  },
  setState() {
    set(state => {
      console.log(state);
      state.foo.bar = state.foo.bar + 1;
    });
  }
}));
```

**Comment by aniiantt** [comment]
> That example is only wrapping `set`. It is possible to wrap both if you wrap `create`:
> 
> ```js
> const immer = config => (set, get, api) => config(fn => set(produce(fn)), get, api);
> const createImmerStore = createState => {
>   const [useStore, api] = create(immer(createState));
>   const setState = api.setState;
>   api.setState = fn => setState(produce(fn));
>   return [useStore, api];
> };
> 
> // Don't call: immer(set => ...
> // `set` will already be wrapped by `createImmerStore`.
> const [useStore, userStoreApi] = createImmerStore(set => ({
>   foo: {
>     bar: 1
>   },
>   setState() {
>     set(state => {
>       console.log(state);
>       state.foo.bar = state.foo.bar + 1;
>     });
>   }
> }));
> ```

👌，I got it
