### ISSUE TITLE
type error when using with immer

### ISSUE THREAD

**Issue by naivefun** [react-spring/zustand#96]
now the signature of set accepts: `export declare type PartialState<T extends State> = Partial<T> | ((state: T) => Partial<T>);` but with immer it requires `(state: T) => void`, or it cannot pass the type checking.

The complete type should be: `export declare type PartialState<T extends State> = Partial<T> | ((state: T) => Partial<T>) | ((state:T) => void);`

**Comment by clawoflight** [comment]
Please fix this, it makes typescript usage quite annoying :)

**Comment by dai-shi** [comment]
Hi, would someone help me understand the issue?
#99 doesn't seem to be the right solution to me.

1. Using immer in custom setter seems to work without #99.
https://codesandbox.io/s/bold-bassi-v2fhq?file=/src/App.tsx
Check zustand.ts:L7 where I comment it out.

2. Using immer middleware fails even with #99.
https://codesandbox.io/s/heuristic-germain-s9sbs?file=/src/App.tsx
Is there better type annotation?

Thanks everyone.

**Comment by dai-shi** [comment]
As I investigate it, #169 should be a better solution.
