### ISSUE TITLE
conflicts with react devtools

### ISSUE THREAD

**Issue by naivefun** [react-spring/zustand#97]
when select component using zustand with react devtools cursor, it gives this:

![image](https://user-images.githubusercontent.com/10683378/77621472-7c92ac80-6f77-11ea-9cc5-199148c3c2df.png)

**Comment by dai-shi** [comment]
Can you reproduce this with v3?

**Comment by dai-shi** [comment]
I think this was a possible bug in v2. Please file a new issue if you find it in v3.
